### ISSUE TITLE
Attempt to run fedora-27 image in OpenShift fails

### ISSUE THREAD

**Issue by adelton** [freeipa/freeipa-container#187]
Attempt to create application in OpenShift on 

```
docker-1.13.1-44.git584d391.fc26.x86_64
selinux-policy-3.13.1-260.18.fc26.noarch
container-selinux-2.40-1.fc26.noarch
```
OpenShift was started as all-on-one setup with oc cluster up, using oc 3.6.1 from https://github.com/openshift/origin/releases/download/v3.6.1/openshift-origin-client-tools-v3.6.1-008f2d5-linux-64bit.tar.gz

The ipaserver-install.log ends with:

```
2018-02-01T12:38:27Z DEBUG Starting external process
2018-02-01T12:38:27Z DEBUG args=/bin/systemctl start messagebus.service
2018-02-01T12:38:27Z DEBUG Process finished, return code=0
2018-02-01T12:38:27Z DEBUG stdout=
2018-02-01T12:38:27Z DEBUG stderr=
2018-02-01T12:38:27Z DEBUG Starting external process
2018-02-01T12:38:27Z DEBUG args=/bin/systemctl is-active messagebus.service
2018-02-01T12:38:27Z DEBUG Process finished, return code=0
2018-02-01T12:38:27Z DEBUG stdout=active

2018-02-01T12:38:27Z DEBUG stderr=
2018-02-01T12:38:27Z DEBUG Starting external process
2018-02-01T12:38:27Z DEBUG args=/bin/systemctl start certmonger.service
2018-02-01T12:38:27Z DEBUG Process finished, return code=0
2018-02-01T12:38:27Z DEBUG stdout=
2018-02-01T12:38:27Z DEBUG stderr=
2018-02-01T12:38:27Z DEBUG Starting external process
2018-02-01T12:38:27Z DEBUG args=/bin/systemctl is-active certmonger.service
2018-02-01T12:38:27Z DEBUG Process finished, return code=0
2018-02-01T12:38:27Z DEBUG stdout=active

2018-02-01T12:38:27Z DEBUG stderr=
2018-02-01T12:38:52Z ERROR Introspect error on :1.1:/org/fedorahosted/certmonger: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2018-02-01T12:38:52Z DEBUG Executing introspect queue due to error
2018-02-01T12:39:17Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 506, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 496, in run_step
    method()
  File "/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py", line 259, in configure_certmonger_renewal
    path = iface.find_ca_by_nickname(name)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

2018-02-01T12:39:17Z DEBUG   [error] DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2018-02-01T12:39:17Z DEBUG   File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 174, in execute
    return_value = self.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 336, in run
    cfgr.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 364, in run
    self.execute()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 388, in execute
    for _nothing in self._executor():
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 430, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 459, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 449, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 420, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 417, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 654, in _configure
    next(executor)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 430, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 459, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 517, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 449, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 514, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 449, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 420, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 417, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/common.py", line 66, in _install
    for _nothing in self._installer(self.parent):
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/__init__.py", line 578, in main
    master_install(self)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 250, in decorated
    func(installer)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 797, in install
    ca.install_step_0(False, None, options)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/ca.py", line 289, in install_step_0
    use_ldaps=standalone)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/cainstance.py", line 448, in configure_instance
    self.start_creation(runtime=runtime)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 506, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 496, in run_step
    method()
  File "/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py", line 259, in configure_certmonger_renewal
    path = iface.find_ca_by_nickname(name)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)

2018-02-01T12:39:17Z DEBUG The ipa-server-install command failed, exception: DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2018-02-01T12:39:17Z ERROR org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

In the audit.log, I only see AVC denials

```
type=AVC msg=audit(1517488935.631:817): avc:  denied  { write } for  pid=12573 comm="ipa-server-conf" name="fd" dev="proc" ino=248798 scontext=system_u:system_r:container_t:s0:c4,c7 tcontext=system_u:system_r:container_t:s0:c4,c7 tclass=dir permissive=0
```

which seems to be https://bugzilla.redhat.com/show_bug.cgi?id=1540963 and hopefully not directly related.

**Comment by adelton** [comment]
One possibility would be to run without those redirects if we don't have working `/dev/console`.

Another possibility is to use something like `socat` to produce the `/dev/console` in that situation, and redirect to that console always.

**Comment by LorbusChris** [comment]
Is there a solution for this, yet?

**Comment by adelton** [comment]
For the record:

On Fedora 26 with `oc cluster up` 3.6.1, the fedora-27 FreeIPA server image works. And I get the `/usr/sbin/ipa-server-configure-first` output in pod's log, not sure what I meant by those comments about `/dev/console`.

On other hosts or other OpenShift versions, I see things failing.

**Comment by adelton** [comment]
For the record, the failures are nondeterministic, I have test runs where fedora-27 images pass on Fedora 27 with OpenShift 3.6.1 and 3.7.2, and then I see them failing again.

**Comment by adelton** [comment]
Hmm, it's weird, the `systemd.service(5)` says

           Behavior of dbus is similar to simple; however, it is expected that
           the daemon acquires a name on the D-Bus bus, as configured by
           BusName=. systemd will proceed with starting follow-up units after
           the D-Bus bus name has been acquired.

Not sure why this does not seem to be the behaviour in containers. We'd likely need some trivial D-Bus service to test it in containers, independently from IPA.

**Comment by stlaz** [comment]
I remember this being a problem on RHEL about one version back, even on the host (https://bugzilla.redhat.com/show_bug.cgi?id=1511221 - there was at least one more BZ like this), but did not see it appear ever since.

**Comment by adelton** [comment]
The issue can also be reproduced using

```
dbus-send --system --type=method_call --print-reply --dest=org.fedorahosted.certmonger /org/fedorahosted/certmonger org.freedesktop.DBus.Introspectable.Introspect
```

instead of that python code.

However, I can only reproduce it with `registry.fedoraproject.org/fedora:2[78]` images when run on RHEL 7.5 host with `docker-1.13.1-63.git94f4240.el7.x86_64`, not with `registry.access.redhat.com/rhel7` image on the same RHEL host, and not when using those `fedora:*` images on Fedora 27 and 28 hosts.

**Comment by adelton** [comment]
For the record, to reproduce on RHEL 7.5 machine with docker running, start systemd-based container with

```
docker run -e container=oci --name=systemd -d --rm registry.fedoraproject.org/fedora:28 /usr/sbin/init
docker exec -ti systemd bash
```

and in that container session run

```
dnf install -y certmonger
systemctl restart certmonger && systemctl is-active certmonger && \
dbus-send --system --type=method_call --print-reply --dest=org.fedorahosted.certmonger /org/fedorahosted/certmonger org.freedesktop.DBus.Introspectable.Introspect
```

to see it fail with

```
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

and then after a while rerun that `dbus-send` command and see it pass.

**Comment by adelton** [comment]
Adding `/usr/lib/systemd/system/certmonger.service.d/wait-for-ready.conf` containing

```
[Service]
ExecStartPost=/bin/bash -c 'while ! dbus-send --system --type=method_call --print-reply --dest=org.fedorahosted.certmonger /org/fedorahosted/certmonger org.freedesktop.DBus.Introspectable.Introspect > /dev/null ; do sleep 5 ; done'
```

to the container makes the `systemctl restart certmonger` wait until the service is actually reachable.

**Comment by rcritten** [comment]
Interesting. I wonder if non-container certmonger should configure something similar since dbus apparently is started but not responding to requests?

**Comment by adelton** [comment]
I was not able to reproduce the failure on the host, outside of the container. I however see a delay in the reply there.

**Comment by adelton** [comment]
@stlaz, I believe we looked into this issue some more but I don't remember what was the conclusion. Do you remember what we tested?

**Comment by adelton** [comment]
I've seen the issue now with fedora-27 image on docker-1.13.1-68.gitdded712.el7.x86_64, outside of OpenShift.

**Comment by hadogenes** [comment]
I had to add `TimeoutSec=300` to _wait-for-ready.conf_

**Comment by adelton** [comment]
Fixed by https://github.com/freeipa/freeipa-container/pull/221.

**Comment by adelton** [comment]
@hadogenes, if you are able to reproduce failure to start for five minutes, could you perhaps investigate more, ideally outside of OpenShift with just Docker daemon, and report it accordingly? Startup of service of `Type=dbus` really shouldn't finish before the service is available on the bus, so we'd need to figure out why it's happening in the first place and report to appropriate upstream -- Docker, systemd, or certmonger.

**Comment by hadogenes** [comment]
300 sec is far too much, but I use freeipa on slow computer with Intel Atom and standard Timeout was too small

**Comment by adelton** [comment]
I have now filed https://bugzilla.redhat.com/show_bug.cgi?id=1656519 to investigate the issue properly on Fedoras.
