### ISSUE TITLE
'less' command is missing from image

### ISSUE THREAD

**Issue by jacksgt** [freeipa/freeipa-container#248]
Hi,

it appears the `less` command is missing from the image (at least the Fedore 27, maybe others too):

```
ipa help commands
ipa: ERROR: non-public: FileNotFoundError: [Errno 2] No such file or directory: 'less': 'less'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipalib/backend.py", line 141, in execute
    return self.Command[_name](*args, **options)
  File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 450, in __call__
    return self.__do_call(*args, **options)
  File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 478, in __do_call
    ret = self.run(*args, **options)
  File "/usr/lib/python3.6/site-packages/ipalib/cli.py", line 854, in run
    writer.write()
  File "/usr/lib/python3.6/site-packages/ipalib/cli.py", line 716, in write
    open_in_pager(data)
  File "/usr/lib/python3.6/site-packages/ipalib/util.py", line 1207, in open_in_pager
    pager_process = subprocess.Popen([pager], stdin=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'less': 'less'
ipa: ERROR: an internal error has occurred
```

Not sure if this is a packaging errors on FreeIPA's side (since the `freeipa` command obviously depends on `less`) or something else, but it should definitely be fixed.

**Comment by stlaz** [comment]
Definitely a FreeIPA bug, paging of long descriptions was added somewhere in 4.7 I believe.

**Comment by stlaz** [comment]
I opened an issue in their bug tracker: https://pagure.io/freeipa/issue/7746

**Comment by jacksgt** [comment]
@stlaz Awesome, thanks!

**Comment by adelton** [comment]
I find it a low priority to add workaround for this to the container image. Closing now, with the hope that the FreeIPA issues will be resolved soon.
