### ISSUE TITLE
Cannot login  through Web UI after upgrading from Fedora 25 to 27

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#252]
I upgraded upgraded my image from `fedora-25` to `fedora-27`. The upgrade completed successfully.

> freeipa    | The IPA services were upgraded
> freeipa    | The ipa-server-upgrade command was successful

But after the upgrade, login using the web UI is failing with message

> Login failed due to an unknown reason.

Apache error log contains the following stack trace, corresponding to the above error
```
 mod_wsgi (pid=1830): Exception occurred processing WSGI script '/usr/share/ipa/wsgi.py'.
 Traceback (most recent call last):
   File "/usr/share/ipa/wsgi.py", line 59, in application
     return api.Backend.wsgi_dispatch(environ, start_response)
   File "/usr/lib/python3.6/site-packages/ipaserver/rpcserver.py", line 267, in __call__
     return self.route(environ, start_response)
   File "/usr/lib/python3.6/site-packages/ipaserver/rpcserver.py", line 279, in route
     return app(environ, start_response)
   File "/usr/lib/python3.6/site-packages/ipaserver/rpcserver.py", line 937, in __call__
     self.kinit(user_principal, password, ipa_ccache_name)
   File "/usr/lib/python3.6/site-packages/ipaserver/rpcserver.py", line 973, in kinit
     pkinit_anchors=[paths.KDC_CERT, paths.KDC_CA_BUNDLE_PEM],
   File "/usr/lib/python3.6/site-packages/ipalib/install/kinit.py", line 127, in kinit_armor
     run(args, env=env, raiseonerr=True, capture_error=True)
   File "/usr/lib/python3.6/site-packages/ipapython/ipautil.py", line 561, in run
     raise CalledProcessError(p.returncode, arg_string, str(output))
 subprocess.CalledProcessError: Command '/usr/bin/kinit -n -c /var/run/ipa/ccaches/armor_1830 -X X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt -X X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem' returned non-zero exit status 1.

```

The issue is similar to the one discussed in the following thread
https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/2ZU6DVAE6TPR7MVR5LCJTWPY53GT75CR/

But in my case, this is the only server. And the ip address is also matching.

```
# KRB5_TRACE="/dev/stderr" kinit -n
[3140] 1541800345.443417: Getting initial credentials for WELLKNOWN/ANONYMOUS@ENNEXA.COM
[3140] 1541800345.443419: Sending request (184 bytes) to ENNEXA.COM
[3140] 1541800345.443420: Initiating TCP connection to stream 10.10.0.106:88
[3140] 1541800345.443421: Sending TCP request to stream 10.10.0.106:88
[3140] 1541800345.443422: Received answer (287 bytes) from stream 10.10.0.106:88
[3140] 1541800345.443423: Terminating TCP connection to stream 10.10.0.106:88
[3140] 1541800345.443424: Response was from master KDC
[3140] 1541800345.443425: Received error from KDC: -1765328359/Additional pre-authentication required
[3140] 1541800345.443428: Processing preauth types: 136, 19, 2, 133
[3140] 1541800345.443429: Selected etype info: etype aes256-cts, salt "ENNEXA.COMWELLKNOWNANONYMOUS", params ""
[3140] 1541800345.443430: Received cookie: MIT
Password for WELLKNOWN/ANONYMOUS@ENNEXA.COM:
[3140] 1541800507.299803: Preauth module encrypted_timestamp (2) (real) returned: -1765328252/Password read interrupted
kinit: Pre-authentication failed: Password read interrupted while getting initial credentials
```

**Comment by adelton** [comment]
Please check if you aren't starting the container with `--privileged` or `--cap-add SYS_ADMIN`, for the remote chance that the system might be hitting some kernel keyring outside of the container.

**Comment by JoyceBabu** [comment]
Privileged mode is not enabled, but `SYS_ADMIN` capability is enabled for the container.

**Comment by adelton** [comment]
Please rerun without `SYS_ADMIN`.

**Comment by jacksgt** [comment]
Hi there, we're also having the same problem even after upgrading from the `fedora-27` to `fedora-29` (i.e. FreeIPA Version 4.7.2).

The upgrade procedure completed just fine, (if you want to I can post the logs, though I don't think they contain any relevant information).

Here is the apache log:
```
 AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
ipa: INFO: *** PROCESS START ***
ipa: INFO: *** PROCESS START ***
ipa: INFO: *** PROCESS START ***
ipa: INFO: *** PROCESS START ***
mod_wsgi (pid=357): Exception occurred processing WSGI script '/usr/share/ipa/wsgi.py'.
Traceback (most recent call last):
  File "/usr/share/ipa/wsgi.py", line 59, in application
    return api.Backend.wsgi_dispatch(environ, start_response)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 268, in __call__
    return self.route(environ, start_response)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 280, in route
    return app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 981, in __call__
    self.kinit(user_principal, password, ipa_ccache_name)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 1017, in kinit
    pkinit_anchors=[paths.KDC_CERT, paths.KDC_CA_BUNDLE_PEM],
  File "/usr/lib/python3.7/site-packages/ipalib/install/kinit.py", line 127, in kinit_armor
    run(args, env=env, raiseonerr=True, capture_error=True)
  File "/usr/lib/python3.7/site-packages/ipapython/ipautil.py", line 574, in run
    p.returncode, arg_string, output_log, error_log
ipapython.ipautil.CalledProcessError: CalledProcessError(Command ['/usr/bin/kinit', '-n', '-c', '/run/ipa/ccaches/armor_357', '-X', 'X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt', '-X', 'X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem'] returned non-zero exit status 1: 'kinit: Pre-authentication failed: Cannot read password while getting initial credentials\\n')
mod_wsgi (pid=356): Exception occurred processing WSGI script '/usr/share/ipa/wsgi.py'.
Traceback (most recent call last):
  File "/usr/share/ipa/wsgi.py", line 59, in application
    return api.Backend.wsgi_dispatch(environ, start_response)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 268, in __call__
    return self.route(environ, start_response)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 280, in route
    return app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 981, in __call__
    self.kinit(user_principal, password, ipa_ccache_name)
  File "/usr/lib/python3.7/site-packages/ipaserver/rpcserver.py", line 1017, in kinit
    pkinit_anchors=[paths.KDC_CERT, paths.KDC_CA_BUNDLE_PEM],
  File "/usr/lib/python3.7/site-packages/ipalib/install/kinit.py", line 127, in kinit_armor
    run(args, env=env, raiseonerr=True, capture_error=True)
  File "/usr/lib/python3.7/site-packages/ipapython/ipautil.py", line 574, in run
    p.returncode, arg_string, output_log, error_log
ipapython.ipautil.CalledProcessError: CalledProcessError(Command ['/usr/bin/kinit', '-n', '-c', '/run/ipa/ccaches/armor_356', '-X', 'X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt', '-X', 'X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem'] returned non-zero exit status 1: 'kinit: Pre-authentication failed: Cannot read password while getting initial credentials\\n')
```

Though kinit works just fine on the command line:
```
KRB5_TRACE='/dev/stderr' kinit admin
[1757] 1544870802.46625: Getting initial credentials for admin@EXAMPLE.COM
[1757] 1544870802.46627: Sending unauthenticated request
[1757] 1544870802.46628: Sending request (187 bytes) to EXAMPLE.COM
[1757] 1544870802.46629: Initiating TCP connection to stream 172.17.0.2:88
[1757] 1544870802.46630: Sending TCP request to stream 172.17.0.2:88
[1757] 1544870802.46631: Received answer (239 bytes) from stream 172.17.0.2:88
[1757] 1544870802.46632: Terminating TCP connection to stream 172.17.0.2:88
[1757] 1544870802.46633: Response was from master KDC
[1757] 1544870802.46634: Received error from KDC: -1765328359/Additional pre-authentication required
[1757] 1544870802.46637: Preauthenticating using KDC method data
[1757] 1544870802.46638: Processing preauth types: PA-FX-FAST (136), PA-ETYPE-INFO2 (19), PA-ENC-TIMESTAMP (2), PA-FX-COOKIE (133)
[1757] 1544870802.46639: Selected etype info: etype aes256-cts, salt "FKSnx.\TzJV&k9+l", params ""
[1757] 1544870802.46640: Received cookie: MIT
Password for admin@EXAMPLE.COM: 
[1757] 1544870807.231593: AS key obtained for encrypted timestamp: aes256-cts/367D
[1757] 1544870807.231595: Encrypted timestamp (for 1544870807.235463): plain 301AA011180F32303138313231353130343634375AA10502030397C7, encrypted A97B01E7034FE272FF062548C0E3ED8AA660423D0577EF4EDFAC0EDA6F3A9BEF2BE49717901119C7E38A4864E40FE8F55ED2CA7DDF9F8434
[1757] 1544870807.231596: Preauth module encrypted_timestamp (2) (real) returned: 0/Success
[1757] 1544870807.231597: Produced preauth for next request: PA-FX-COOKIE (133), PA-ENC-TIMESTAMP (2)
[1757] 1544870807.231598: Sending request (282 bytes) to EXAMPLE.COM
[1757] 1544870807.231599: Initiating TCP connection to stream 172.17.0.2:88
[1757] 1544870807.231600: Sending TCP request to stream 172.17.0.2:88
[1757] 1544870807.231601: Received answer (738 bytes) from stream 172.17.0.2:88
[1757] 1544870807.231602: Terminating TCP connection to stream 172.17.0.2:88
[1757] 1544870807.231603: Response was from master KDC
[1757] 1544870807.231604: Processing preauth types: PA-ETYPE-INFO2 (19)
[1757] 1544870807.231605: Selected etype info: etype aes256-cts, salt "FKSnx.\TzJV&k9+l", params ""
[1757] 1544870807.231606: Produced preauth for next request: (empty)
[1757] 1544870807.231607: AS key determined by preauth: aes256-cts/367D
[1757] 1544870807.231608: Decrypted AS reply; session key is: aes256-cts/557C
[1757] 1544870807.231609: FAST negotiation: available
[1757] 1544870807.231610: Initializing FILE:/tmp/krb5cc_0 with default princ admin@EXAMPLE.COM
[1757] 1544870807.231611: Storing admin@EXAMPLE.COM -> krbtgt/EXAMPLE.COM@EXAMPLE.COM in FILE:/tmp/krb5cc_0
[1757] 1544870807.231612: Storing config in FILE:/tmp/krb5cc_0 for krbtgt/EXAMPLE.COM@EXAMPLE.COM: fast_avail: yes
[1757] 1544870807.231613: Storing admin@EXAMPLE.COM -> krb5_ccache_conf_data/fast_avail/krbtgt\/EXAMPLE.COM\@EXAMPLE.COM@X-CACHECONF: in FILE:/tmp/krb5cc_0
[1757] 1544870807.231614: Storing config in FILE:/tmp/krb5cc_0 for krbtgt/EXAMPLE.COM@EXAMPLE.COM: pa_type: 2
[1757] 1544870807.231615: Storing admin@EXAMPLE.COM -> krb5_ccache_conf_data/pa_type/krbtgt\/EXAMPLE.COM\@EXAMPLE.COM@X-CACHECONF: in FILE:/tmp/krb5cc_0
```

---

We're running the container as follows:
```
docker run \
 -h 'ipa01.example.com' --net bridge -m 0b -e IPA_SERVER_IP=192.168.2.15 \
 -e IPA_SERVER_HOSTNAME=ipa01.example.com \
 -v /data-fedora29/ipa:/data:Z \
 -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
 --tmpfs /tmp --tmpfs /run --sysctl net.ipv6.conf.all.disable_ipv6=0 --cap-add SYS_TIME --name freeipa \
  freeipa/freeipa-server:fedora-29
```

@JoyceBabu is your certmonger daemon running (`systemctl status certmonger`)? For us, it crashes after starting the container the first time, but can later be started manually without any issues:
```
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a 
reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

Though I'm not sure if this is related.

**Comment by adelton** [comment]
I confirm the failure in the Fedora 25 -> Fedora 27 image upgrade situation.

Furthermore, rerunning that `kinit -n ...` command in the FreeIPA server container asks for a password:

```
[root@ipa /]# /usr/bin/kinit -n -c /var/run/ipa/ccaches/armor_2591 -X X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt -X X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
Password for WELLKNOWN/ANONYMOUS@EXAMPLE.TEST: 
kinit: Pre-authentication failed: Password read interrupted while getting initial credentials
```

Further upgrade to Fedora 29 image does not fix the issue.

We likely need some expertise from the FreeIPA team. @abbra, any idea what we should be looking for?

**Comment by jacksgt** [comment]
Thanks for your feedback!

I tried both of the workarounds, unfortunately neither of them seem to have had any success.

Initial status:
```
$ ipa-pkinit-manage status
PKINIT is disabled
The ipa-pkinit-manage command was successful

$ ls -l /var/kerberos/krb5kdc/
total 20
-rw-r--r-- 1 root root    0 Dec 15 10:07 cacert.pem
-rw------- 1 root root   22 Sep  6  2017 kadm5.acl
-rw------- 1 root root  669 Dec 15 10:07 kdc.conf
-rw------- 1 root root  458 Oct  9 20:59 kdc.conf.rpmnew
-rw-r--r-- 1 root root 1415 Oct 27 14:44 kdc.crt
-rw------- 1 root root 1708 Oct 27 14:44 kdc.key
```

[Workaround by jaredl](https://pagure.io/freeipa/issue/7200#comment-543848):
```
$ getcert resubmit -vwf /var/kerberos/krb5kdc/kdc.crt
Resubmitting "20181027144409" to "SelfSign".
State GENERATING_CSR, stuck: no.
State POST_SAVED_CERT, stuck: no.
State MONITORING, stuck: no.
```
As mentioned in the [Pagure Ticket](https://pagure.io/freeipa/issue/7200), the certificate is supposed to be signed by IPA, not self-signed.

Therefore I ran the [second workaround by abbra](https://pagure.io/freeipa/issue/7200#comment-543927):
```
$ rm /var/kerberos/krb5kdc/kdc.{crt,key}
$ ipa-pkinit-manage --verbose enable
ipalib.install.sysrestore: DEBUG: Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
ipapython.admintool: DEBUG: Not logging to a file
ipalib.plugable: DEBUG: importing all plugin modules in ipaserver.plugins...
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.aci
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.automember
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.automount
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.baseldap
ipalib.plugable: DEBUG: ipaserver.plugins.baseldap is not a valid plugin module
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.baseuser
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.batch
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.ca
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.caacl
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.cert
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.certmap
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.certprofile
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.config
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.delegation
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.dns
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.dnsserver
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.dogtag
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.domainlevel
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.group
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.hbac
ipalib.plugable: DEBUG: ipaserver.plugins.hbac is not a valid plugin module
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.hbacrule
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.hbacsvc
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.hbacsvcgroup
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.hbactest
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.host
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.hostgroup
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.idrange
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.idviews
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.internal
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.join
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.krbtpolicy
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.ldap2
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.location
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.migration
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.misc
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.netgroup
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.otp
ipalib.plugable: DEBUG: ipaserver.plugins.otp is not a valid plugin module
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.otpconfig
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.otptoken
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.passwd
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.permission
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.ping
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.pkinit
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.privilege
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.pwpolicy
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.rabase
ipalib.plugable: DEBUG: ipaserver.plugins.rabase is not a valid plugin module
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.radiusproxy
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.realmdomains
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.role
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.schema
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.selfservice
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.selinuxusermap
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.server
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.serverrole
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.serverroles
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.service
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.servicedelegation
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.session
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.stageuser
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.sudo
ipalib.plugable: DEBUG: ipaserver.plugins.sudo is not a valid plugin module
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.sudocmd
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.sudocmdgroup
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.sudorule
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.topology
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.trust
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.user
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.vault
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.virtual
ipalib.plugable: DEBUG: ipaserver.plugins.virtual is not a valid plugin module
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.whoami
ipalib.plugable: DEBUG: importing plugin module ipaserver.plugins.xmlserver
ipalib.backend: DEBUG: Created connection context.ldap2_139624142027520
ipalib.frontend: DEBUG: raw: ca_is_enabled(version='2.230')
ipalib.frontend: DEBUG: ca_is_enabled(version='2.230')
ipapython.ipaldap: DEBUG: retrieving schema for SchemaCache url=ldapi://%2fvar%2frun%2fslapd-EXAMPLE-COM.socket conn=<ldap.ldapobject.SimpleLDAPObject object at 0x7efcc6d8ab00>
ipalib.frontend: DEBUG: raw: config_show(version='2.230')
ipalib.frontend: DEBUG: config_show(rights=False, all=False, raw=False, version='2.230')
ipalib.frontend: DEBUG: raw: ca_is_enabled(version='2.230')
ipalib.frontend: DEBUG: ca_is_enabled(version='2.230')
ipalib.install.sysrestore: DEBUG: Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
ipalib.install.sysrestore: DEBUG: Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
ipaserver.install.service: DEBUG: Configuring Kerberos KDC (krb5kdc)
Configuring Kerberos KDC (krb5kdc)
ipaserver.install.service: DEBUG:   [1/1]: installing X509 Certificate for PKINIT
  [1/1]: installing X509 Certificate for PKINIT
ipalib.install.certmonger: DEBUG: certmonger request is in state dbus.String('NEWLY_ADDED', variant_level=1)
ipalib.install.certmonger: DEBUG: certmonger request is in state dbus.String('GENERATING_KEY_PAIR', variant_level=1)
ipalib.install.certmonger: DEBUG: certmonger request is in state dbus.String('MONITORING', variant_level=1)
ipalib.install.certmonger: DEBUG: Cert request 20181225132222 was successful
ipaserver.install.service: DEBUG: service KDC has all config values set
ipaserver.install.service: DEBUG: step duration: krb5kdc setup_pkinit 23.94 sec
ipaserver.install.service: DEBUG: Done configuring Kerberos KDC (krb5kdc).
Done configuring Kerberos KDC (krb5kdc).
ipaserver.install.service: DEBUG: service duration: krb5kdc 23.95 sec
ipapython.ipautil: DEBUG: Starting external process
ipapython.ipautil: DEBUG: args=['/bin/systemctl', 'restart', 'krb5kdc.service']
ipapython.ipautil: DEBUG: Process finished, return code=0
ipapython.ipautil: DEBUG: stdout=
ipapython.ipautil: DEBUG: stderr=
ipapython.ipautil: DEBUG: Starting external process
ipapython.ipautil: DEBUG: args=['/bin/systemctl', 'is-active', 'krb5kdc.service']
ipapython.ipautil: DEBUG: Process finished, return code=0
ipapython.ipautil: DEBUG: stdout=active
ipapython.ipautil: DEBUG: stderr=
ipaplatform.base.services: DEBUG: Restart of krb5kdc.service complete
ipaserver.install.service: DEBUG: service KDC: config string pkinitEnabled already set
ipaserver.install.service: DEBUG: service KDC has already enabled config values ['pkinitEnabled']
ipalib.backend: DEBUG: Destroyed connection context.ldap2_139624142027520
ipapython.admintool: INFO: The ipa-pkinit-manage command was successful

$ ipa-pkinit-manage status
PKINIT is enabled
The ipa-pkinit-manage command was successful

$ getcert resubmit -vwf /var/kerberos/krb5kdc/kdc.crt
Resubmitting "20181225132222" to "IPA".
State GENERATING_CSR, stuck: no.
State SUBMITTING, stuck: no.
State SAVING_CERT, stuck: no.
State POST_SAVED_CERT, stuck: no.
State MONITORING, stuck: no.
```

This looks more promising, but unfortunately I still can't log into the WebUI (even after restarting the IPA services).
Apache still has the same error message as described in [my previous comment](https://github.com/freeipa/freeipa-container/issues/252#issuecomment-447560683).

Certmonger is up and running:
```
Dec 25 13:18:03 ipa01 /renew_kdc_cert[20196]: restarting krb5kdc
Dec 25 13:18:04 ipa01 certmonger[20203]: Certificate in file "/var/kerberos/krb5kdc/kdc.crt" issued by CA and saved.
Dec 25 13:22:30 ipa01 /renew_kdc_cert[20373]: restarting krb5kdc
Dec 25 13:22:30 ipa01 certmonger[20380]: Certificate in file "/var/kerberos/krb5kdc/kdc.crt" issued by CA and saved.
```

**Comment by adelton** [comment]
In general, we might need some better testing of upgraded setups. For example, when I run Fedora 25 -> upgrade to 26 -> upgrade to 27, and compare it to data volume of the fresh Fedora 27 installation, I see diffs like

```
diff -ru /tmp/freeipa-test-fedora-25-26-27/data/etc/ipa/kdcproxy/ipa-kdc-proxy.conf /tmp/freeipa-test-fedora-27/data/etc/ipa/kdcproxy/ipa-kdc-proxy.conf
--- /tmp/freeipa-test-fedora-25-26-27/data/etc/ipa/kdcproxy/ipa-kdc-proxy.conf     2018-12-24 12:39:00.000000000 +0100
+++ /tmp/freeipa-test-fedora-27/data/etc/ipa/kdcproxy/ipa-kdc-proxy.conf        2018-12-24 14:11:35.477980372 +0100
@@ -16,9 +16,9 @@
 
 WSGIDaemonProcess kdcproxy processes=2 threads=15 maximum-requests=5000 \
   user=kdcproxy group=kdcproxy display-name=%{GROUP}
-WSGIImportScript /usr/lib/python2.7/site-packages/kdcproxy/__init__.py \
+WSGIImportScript /usr/share/ipa/kdcproxy.wsgi \
   process-group=kdcproxy application-group=kdcproxy
-WSGIScriptAlias /KdcProxy /usr/lib/python2.7/site-packages/kdcproxy/__init__.py
+WSGIScriptAlias /KdcProxy /usr/share/ipa/kdcproxy.wsgi
 WSGIScriptReloading Off
 
 <Location "/KdcProxy">
diff -ru /tmp/freeipa-test-fedora-25-26-27/data/etc/krb5.conf /tmp/freeipa-test-fedora-27/data/etc/krb5.conf
--- /tmp/freeipa-test-fedora-25-26-27/data/etc/krb5.conf   2018-12-24 14:05:29.000000000 +0100
+++ /tmp/freeipa-test-fedora-27/data/etc/krb5.conf      2018-12-24 14:16:41.131816697 +0100
@@ -21,7 +21,8 @@
   master_kdc = ipa.example.test:88
   admin_server = ipa.example.test:749
   default_domain = example.test
-  pkinit_anchors = FILE:/etc/ipa/ca.crt
+  pkinit_anchors = FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
+  pkinit_pool = FILE:/var/lib/ipa-client/pki/ca-bundle.pem
 }
 
 [domain_realm]
```

Neither of these seems to make the difference for this particular issue (when I update the config file with the one from fresh Fedora 27 installation, the WebUI logon still fails) but we likely want to start adding upgrade tests to check that some config files (or symlinks) that we care about have the fresh content after upgrade, matching what new installation would do.

**Comment by adelton** [comment]
@Tiboris, @abbra, any ideas what to look for in this upgrade issue?

**Comment by tiran** [comment]
https://github.com/freeipa/freeipa/commit/0c0a392dd0c8a7d77a1e9f571cf44c6af446c07f  take care of KDC proxy configuration. The config file gets updated in master and 4.7 branch.

**Comment by adelton** [comment]
I've tested upgrade from `.fedora-25` to `.fedora-27` a to `.fedora-28`, and compared it to fresh `.fedora-28` installation.

The `/etc/ipa/kdcproxy/ipa-kdc-proxy.conf` on the upgraded setup (to `.fedora-28`) matches the content on fresh `.fedora-28` container. So that part seems to be resolved on latest Fedora 28.

On the other hand, the `/etc/krb5.conf` does not get upgraded, so it still has `pkinit_anchors = FILE:/etc/ipa/ca.crt` after the upgrade, not matching the fresh installation. Might that be a problem?

**Comment by abbra** [comment]
Yes, it most likely an issue in itself. Can you file a separate freeipa issue for that on pagure.io/freeipa/?

**Comment by adelton** [comment]
I've filed https://pagure.io/freeipa/issue/7875 now.

**Comment by martialblog** [comment]
@adelton Awesome! Thanks!

**Comment by adelton** [comment]
@JoyceBabu, were you able to get the WebUI working, perhaps by manually updating the `krb5.conf` (if that was the root of the problem)?

**Comment by JoyceBabu** [comment]
@adelton I did not get a chance to try the `fedora-27` image after creating the ticket. I'll try it this weekend.

**Comment by JoyceBabu** [comment]
The issue still not resolved. I am still seeing the same error.

I tried copying `krb5.conf` and `ipa-kdc-proxy.conf` from a fresh `fedora-27` container, and tried enabling `PKINIT` and regenerating `kdc.{crt,key}`.

When upgrading from `25` to `27`, `/var/lib/ipa-client/pki/` directory is empty. Could this be the problem?

**Comment by JoyceBabu** [comment]
Okay, that was the problem.

The solution is

- Copy `/etc/krb5.conf` from `fedora-27` container
- Copy `/etc/ipa/ca.crt` to `/var/lib/ipa-client/pki/kdc-ca-bundle.pem` and `/var/lib/ipa-client/pki/ca-bundle.pem`

      cp /etc/ipa/ca.crt /var/lib/ipa-client/pki/kdc-ca-bundle.pem
      cp /etc/ipa/ca.crt /var/lib/ipa-client/pki/ca-bundle.pem
- Regenerate `/var/kerberos/krb5kdc/kdc.crt` with

      getcert resubmit -vwf /var/kerberos/krb5kdc/kdc.crt

- Verify by running

      /usr/bin/kinit -n -c /var/run/ipa/ccaches/armor_482 -X X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt -X X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem

**Comment by JoyceBabu** [comment]
After fixing the above issue, I was able to upgrade all the way up to `fedora-30` without any issues. I did see some warnings about some links in `/data-template` from being skipped, since the `/data` target was a file. I resolved those by deleting the files from `/data` before running `ipa-server-upgrade`.

**Comment by rcritten** [comment]
/etc/httpd/conf.d/ipa-kdc-proxy.conf is not regenerated on upgrades and is un-versioned so updates to the template will not be automatically applied. I've opened https://pagure.io/freeipa/issue/8025 for that.

**Comment by martialblog** [comment]
@JoyceBabu Hi, thanks for the update. We'll try your solution and then report back

**Comment by martialblog** [comment]
@JoyceBabu our system was similar to your findings:

The system after the upgrade looked like this:
```
ls -l /etc/yp.conf 
 /etc/yp.conf -> /data/etc/yp.conf
cat /etc/yp.conf
cat: /etc/yp.conf: No such file or directory

ls -l /etc/rndc.key 
 /etc/rndc.key -> /data/etc/rndc.key
cat /etc/rndc.key
cat: /etc/rndc.key: No such file or directory

ls /var/lib/ipa-client/pki/
 empty

cat /etc/krb5.conf
pkinit_anchors = FILE:/etc/ipa/ca.crt

 /usr/bin/kinit -n -c /var/run/ipa/ccaches/armor_482 -X X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt -X X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
Password for WELLKNOWN/ANONYMOUS@DOMAIN.DE:
```

After your solution:

```
 /usr/bin/kinit -n -c /var/run/ipa/ccaches/armor_482 -X X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt -X X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem

echo $?
0
```

**Comment by JoyceBabu** [comment]
@martialblog Thank you for the confirmation.

@adelton Should I close this ticket, or do you want me to keep this open since this is actually an upgrade issue?

**Comment by adelton** [comment]
I assume that the same problem will not manifest itself again for a couple of releases (FreeIPA and Fedora), and if people still need to upgrade from Fedora 27, they can use the workaround.

If these assumptions are correct, I'd just close this issue and leave the https://pagure.io/freeipa/issue/8025 to handle the upgrades properly in the future.

**Comment by adelton** [comment]
Closing per above comment.

**Comment by zx1986** [comment]
> Okay, that was the problem.
> 
> The solution is
> 
> * Copy `/etc/krb5.conf` from `fedora-27` container
> * Copy `/etc/ipa/ca.crt` to `/var/lib/ipa-client/pki/kdc-ca-bundle.pem` and `/var/lib/ipa-client/pki/ca-bundle.pem`
>   ```
>   cp /etc/ipa/ca.crt /var/lib/ipa-client/pki/kdc-ca-bundle.pem
>   cp /etc/ipa/ca.crt /var/lib/ipa-client/pki/ca-bundle.pem
>   ```
> * Regenerate `/var/kerberos/krb5kdc/kdc.crt` with
>   ```
>   getcert resubmit -vwf /var/kerberos/krb5kdc/kdc.crt
>   ```
> * Verify by running
>   ```
>   /usr/bin/kinit -n -c /var/run/ipa/ccaches/armor_482 -X X509_anchors=FILE:/var/kerberos/krb5kdc/kdc.crt -X X509_anchors=FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
>   ```

I got `kinit: Preauthentication failed while getting initial credentials`  :-(

Ubuntu Server 18.04
