### ISSUE TITLE
Failed to set perms 

### ISSUE THREAD

**Issue by corecache** [freeipa/freeipa-container#282]
**Type**: 
Docker container with nginx SSL reverse proxy

**Exec**: 
```docker run -ti --name freeipa-server -h auth.domain -v free-ipa_data:/data -v /sys/fs/cgroup:/sys/fs/cgroup:ro --sysctl net.ipv6.conf.lo.disable_ipv6=0 --tmpfs /run --tmpfs /tmp -p 127.0.0.1:5080:80 -p 127.0.0.1:5443:443 -p 127.0.0.1:5389:389 -p 127.0.0.1:5088:88 freeipa/freeipa-server:centos-7```

**SSL Proxy Configuration**:
```
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;

        add_header              X-Frame-Options DENY;
        add_header              X-Content-Type-Options nosniff;

        proxy_connect_timeout   150;
        proxy_send_timeout      100;
        proxy_read_timeout      100;
        proxy_buffers           4 32k;
        client_max_body_size    200M;
        client_body_buffer_size 512k;
        keepalive_timeout       5;

        proxy_pass https://127.0.0.1:5443/;
```

**Version**: 
freeipa/freeipa-server:centos-7 (10 days ago, cant seem to find the sha1 commit hash, please include it in the future)

**Description**:
Installs successfully
Trying to login produces this error message after turning debug on in default.conf

**Logs**
```
[Thu Sep 05 14:16:33.386993 2019] [:warn] [pid 835] [client 172.17.0.2:36772] failed to set perms (3140) on file (/var/run/ipa/ccaches/admin@DOMAIN)!, referer: https://auth.domain/ipa/xml
[Thu Sep 05 14:16:33.388500 2019] [:error] [pid 407] ipa: DEBUG: WSGI wsgi_dispatch.__call__:
[Thu Sep 05 14:16:33.388773 2019] [:error] [pid 407] ipa: DEBUG: WSGI jsonserver_session.__call__:
[Thu Sep 05 14:16:33.413377 2019] [:error] [pid 407] ipa: DEBUG: Created connection context.ldap2_139793843529296
[Thu Sep 05 14:16:33.413590 2019] [:error] [pid 407] ipa: DEBUG: WSGI jsonserver.__call__:
[Thu Sep 05 14:16:33.413745 2019] [:error] [pid 407] ipa: DEBUG: WSGI WSGIExecutioner.__call__:
[Thu Sep 05 14:16:33.414547 2019] [:error] [pid 407] ipa: DEBUG: raw: schema(version=u'2.170')
[Thu Sep 05 14:16:33.414911 2019] [:error] [pid 407] ipa: DEBUG: schema(version=u'2.170')
[Thu Sep 05 14:16:33.415745 2019] [:error] [pid 407] ipa: ERROR: non-public: AttributeError: locked: cannot set API._schema to {}
[Thu Sep 05 14:16:33.415775 2019] [:error] [pid 407] Traceback (most recent call last):
[Thu Sep 05 14:16:33.415787 2019] [:error] [pid 407]   File "/usr/lib/python2.7/site-packages/ipaserver/rpcserver.py", line 369, in wsgi_execute
[Thu Sep 05 14:16:33.415800 2019] [:error] [pid 407]     result = command(*args, **options)
[Thu Sep 05 14:16:33.415812 2019] [:error] [pid 407]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 450, in __call__
[Thu Sep 05 14:16:33.415825 2019] [:error] [pid 407]     return self.__do_call(*args, **options)
[Thu Sep 05 14:16:33.415836 2019] [:error] [pid 407]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 478, in __do_call
[Thu Sep 05 14:16:33.415848 2019] [:error] [pid 407]     ret = self.run(*args, **options)
[Thu Sep 05 14:16:33.415860 2019] [:error] [pid 407]   File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 800, in run
[Thu Sep 05 14:16:33.415872 2019] [:error] [pid 407]     return self.execute(*args, **options)
[Thu Sep 05 14:16:33.415884 2019] [:error] [pid 407]   File "/usr/lib/python2.7/site-packages/ipaserver/plugins/schema.py", line 840, in execute
[Thu Sep 05 14:16:33.415896 2019] [:error] [pid 407]     setattr(self.api, "_schema", {})
[Thu Sep 05 14:16:33.415908 2019] [:error] [pid 407]   File "/usr/lib/python2.7/site-packages/ipalib/base.py", line 134, in __setattr__
[Thu Sep 05 14:16:33.415920 2019] [:error] [pid 407]     SET_ERROR % (self.__class__.__name__, name, value)
[Thu Sep 05 14:16:33.415931 2019] [:error] [pid 407] AttributeError: locked: cannot set API._schema to {}
```

**Comment by adelton** [comment]
What does the following command output when you run it in the container
```
grep -r GssapiDelegCcachePerms /etc/httpd/conf.d/ipa.conf
```
?

**Comment by corecache** [comment]
> 
> 
> What does the following command output when you run it in the container
> 
> ```
> grep -r GssapiDelegCcachePerms /etc/httpd/conf.d/ipa.conf
> ```
> 
> ?

```
[root@auth /]# grep -r GssapiDelegCcachePerms /etc/httpd/conf.d/ipa.conf
  GssapiDelegCcachePerms mode:0660 gid:ipaapi
  GssapiDelegCcachePerms mode:0660 gid:ipaapi
```

**Comment by adelton** [comment]
I see the same 0600 permission on an FreeIPA installation on a host, outside of container.

I was more curious about that `3140` value in the error message.

**Comment by adelton** [comment]
What's in your `ipa-server-install-options` file?

**Comment by adelton** [comment]
It seems we've lost the traction here.
