### ISSUE TITLE
freeipa/freeipa-server:fedora-32 fails: No valid Negotiate header in server response

### ISSUE THREAD

**Issue by tiran** [freeipa/freeipa-container#325]
Installation of ``docker.io/freeipa/freeipa-server:fedora-32`` (image id ``0350c716fe33``) fails in podman on Fedora 32. Installation fails in ``ipa-client-install`` step with message ``No valid Negotiate header in server response``. The error is fully reproducible. 3 out of 3 attempts have failed.

```
# podman run --name freeipa-server-container -ti -h ipa.example.test -e PASSWORD=Secret123 --read-only --privileged -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:fedora-32 exit-on-finished -U -r EXAMPLE.TEST --no-ntp
...
Writing manifest to image destination
Storing signatures
systemd v245.6-2.fc32 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Installed transient /etc/machine-id file.
Mon Jul 13 08:56:26 UTC 2020 /usr/sbin/ipa-server-configure-first 

The log file for this installation can be found in /var/log/ipaserver-install.log
==============================================================================
This program will set up the FreeIPA Server.
Version 4.8.7

This includes:
  * Configure a stand-alone CA (dogtag) for certificate management
  * Create and configure an instance of Directory Server
  * Create and configure a Kerberos Key Distribution Center (KDC)
  * Configure Apache (httpd)
  * Configure the KDC to enable PKINIT

Excluded by options:
  * Configure the NTP client (chronyd)

The domain name has been determined based on the host name.


The IPA Master Server will be configured with:
Hostname:       ipa.example.test
IP address(es): 10.88.0.31
Domain name:    example.test
Realm name:     EXAMPLE.TEST

The CA will be configured with:
Subject DN:   CN=Certificate Authority,O=EXAMPLE.TEST
Subject base: O=EXAMPLE.TEST
Chaining:     self-signed

Disabled p11-kit-proxy
Configuring directory server (dirsrv). Estimated time: 30 seconds
  [1/44]: creating directory server instance
  [2/44]: configure autobind for root
  [3/44]: stopping directory server
  [4/44]: updating configuration in dse.ldif
  [5/44]: starting directory server
  [6/44]: adding default schema
  [7/44]: enabling memberof plugin
  [8/44]: enabling winsync plugin
  [9/44]: configure password logging
  [10/44]: configuring replication version plugin
  [11/44]: enabling IPA enrollment plugin
  [12/44]: configuring uniqueness plugin
  [13/44]: configuring uuid plugin
  [14/44]: configuring modrdn plugin
  [15/44]: configuring DNS plugin
  [16/44]: enabling entryUSN plugin
  [17/44]: configuring lockout plugin
  [18/44]: configuring topology plugin
  [19/44]: creating indices
  [20/44]: enabling referential integrity plugin
  [21/44]: configuring certmap.conf
  [22/44]: configure new location for managed entries
  [23/44]: configure dirsrv ccache and keytab
  [24/44]: enabling SASL mapping fallback
  [25/44]: restarting directory server
  [26/44]: adding sasl mappings to the directory
  [27/44]: adding default layout
  [28/44]: adding delegation layout
  [29/44]: creating container for managed entries
  [30/44]: configuring user private groups
  [31/44]: configuring netgroups from hostgroups
  [32/44]: creating default Sudo bind user
  [33/44]: creating default Auto Member layout
  [34/44]: adding range check plugin
  [35/44]: creating default HBAC rule allow_all
  [36/44]: adding entries for topology management
  [37/44]: initializing group membership
  [38/44]: adding master entry
  [39/44]: initializing domain level
  [40/44]: configuring Posix uid/gid generation
  [41/44]: adding replication acis
  [42/44]: activating sidgen plugin
  [43/44]: activating extdom plugin
  [44/44]: configuring directory to start on boot
Done configuring directory server (dirsrv).
Configuring Kerberos KDC (krb5kdc)
  [1/10]: adding kerberos container to the directory
  [2/10]: configuring KDC
  [3/10]: initialize kerberos container
  [4/10]: adding default ACIs
  [5/10]: creating a keytab for the directory
  [6/10]: creating a keytab for the machine
  [7/10]: adding the password extension to the directory
  [8/10]: creating anonymous principal
  [9/10]: starting the KDC
  [10/10]: configuring KDC to start on boot
Done configuring Kerberos KDC (krb5kdc).
Configuring kadmin
  [1/2]: starting kadmin 
  [2/2]: configuring kadmin to start on boot
Done configuring kadmin.
Configuring ipa-custodia
  [1/5]: Making sure custodia container exists
  [2/5]: Generating ipa-custodia config file
  [3/5]: Generating ipa-custodia keys
  [4/5]: starting ipa-custodia 
  [5/5]: configuring ipa-custodia to start on boot
Done configuring ipa-custodia.
Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
  [1/30]: configuring certificate server instance
  [2/30]: Add ipa-pki-wait-running
  [3/30]: secure AJP connector
  [4/30]: reindex attributes
  [5/30]: exporting Dogtag certificate store pin
  [6/30]: stopping certificate server instance to update CS.cfg
  [7/30]: backing up CS.cfg
  [8/30]: disabling nonces
  [9/30]: set up CRL publishing
  [10/30]: enable PKIX certificate path discovery and validation
  [11/30]: starting certificate server instance
  [12/30]: configure certmonger for renewals
  [13/30]: requesting RA certificate from CA
  [14/30]: setting audit signing renewal to 2 years
  [15/30]: restarting certificate server
  [16/30]: publishing the CA certificate
  [17/30]: adding RA agent as a trusted user
  [18/30]: authorizing RA to modify profiles
  [19/30]: authorizing RA to manage lightweight CAs
  [20/30]: Ensure lightweight CAs container exists
  [21/30]: configure certificate renewals
  [22/30]: Configure HTTP to proxy connections
  [23/30]: restarting certificate server
  [24/30]: updating IPA configuration
  [25/30]: enabling CA instance
  [26/30]: migrating certificate profiles to LDAP
  [27/30]: importing IPA certificate profiles
  [28/30]: adding default CA ACL
  [29/30]: adding 'ipa' CA entry
  [30/30]: configuring certmonger renewal for lightweight CAs
Done configuring certificate server (pki-tomcatd).
Configuring directory server (dirsrv)
  [1/3]: configuring TLS for DS instance
  [2/3]: adding CA certificate entry
  [3/3]: restarting directory server
Done configuring directory server (dirsrv).
Configuring ipa-otpd
  [1/2]: starting ipa-otpd 
  [2/2]: configuring ipa-otpd to start on boot
Done configuring ipa-otpd.
Configuring the web interface (httpd)
  [1/21]: stopping httpd
  [2/21]: backing up ssl.conf
  [3/21]: disabling nss.conf
  [4/21]: configuring mod_ssl certificate paths
  [5/21]: setting mod_ssl protocol list
  [6/21]: configuring mod_ssl log directory
  [7/21]: disabling mod_ssl OCSP
  [8/21]: adding URL rewriting rules
  [9/21]: configuring httpd
Nothing to do for configure_httpd_wsgi_conf
  [10/21]: setting up httpd keytab
  [11/21]: configuring Gssproxy
  [12/21]: setting up ssl
  [13/21]: configure certmonger for renewals
  [14/21]: publish CA cert
  [15/21]: clean up any existing httpd ccaches
  [16/21]: configuring SELinux for httpd
  [17/21]: create KDC proxy config
  [18/21]: enable KDC proxy
  [19/21]: starting httpd
  [20/21]: configuring httpd to start on boot
  [21/21]: enabling oddjobd
Done configuring the web interface (httpd).
Configuring Kerberos KDC (krb5kdc)
  [1/1]: installing X509 Certificate for PKINIT
Done configuring Kerberos KDC (krb5kdc).
Applying LDAP updates
Upgrading IPA:. Estimated time: 1 minute 30 seconds
  [1/10]: stopping directory server
  [2/10]: saving configuration
  [3/10]: disabling listeners
  [4/10]: enabling DS global lock
  [5/10]: disabling Schema Compat
  [6/10]: starting directory server
  [7/10]: upgrading server
  [8/10]: stopping directory server
  [9/10]: restoring configuration
  [10/10]: starting directory server
Done.
Restarting the KDC
Configuring client side components
This program will set up FreeIPA client.
Version 4.8.7

Using existing certificate '/etc/ipa/ca.crt'.
Client hostname: ipa.example.test
Realm: EXAMPLE.TEST
DNS Domain: example.test
IPA Server: ipa.example.test
BaseDN: dc=example,dc=test

Configured sudoers in /data/etc/authselect/user-nsswitch.conf
Configured /etc/sssd/sssd.conf
No valid Negotiate header in server response
The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
Configuration of client side components failed!
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
FreeIPA server configuration failed.
```

```
# podman images
REPOSITORY                        TAG        IMAGE ID      CREATED      SIZE
docker.io/freeipa/freeipa-server  fedora-32  0350c716fe33  2 weeks ago  876 MB
```

## ipaclient-install log
```
2020-07-13T08:59:57Z DEBUG failed to find session_cookie in persistent storage for principal 'host/ipa.example.test@EXAMPLE.TEST'
2020-07-13T08:59:57Z DEBUG trying https://ipa.example.test/ipa/json
2020-07-13T08:59:57Z DEBUG Created connection context.rpcclient_140184898891152
2020-07-13T08:59:57Z DEBUG [try 1]: Forwarding 'schema' to json server 'https://ipa.example.test/ipa/json'
2020-07-13T08:59:57Z DEBUG New HTTP connection (ipa.example.test)
2020-07-13T08:59:57Z DEBUG HTTP connection destroyed (ipa.example.test)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ipaclient/remote_plugins/__init__.py", line 126, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.8/site-packages/ipalib/rpc.py", line 676, in _auth_complete
    raise errors.KerberosError(
ipalib.errors.KerberosError: No valid Negotiate header in server response
2020-07-13T08:59:57Z DEBUG Destroyed connection context.rpcclient_140184898891152
```

## httpd error log
```
[Mon Jul 13 08:59:57.790874 2020] [auth_gssapi:error] [pid 3246:tid 140703707416320] [client 10.88.0.31:40184] GSS ERROR gss_acquire_cred[_from]() failed to get server creds: [Unspecified GSS failure.  Minor code may provide more information ( SPNEGO cannot find mechanisms to negotiate)], referer: https://ipa.example.test/ipa/xml
```

**Comment by adelton** [comment]
Please do not use `--privileged`, ever.
Please rerun the command without that option.

**Comment by tiran** [comment]
Without ``--privileged`` podman run fails immediately:

```
# podman run --name freeipa-server-container -ti -h ipa.example.test -e PASSWORD=Secret123 --read-only -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:fedora-32 exit-on-finished -U -r EXAMPLE.TEST --no-ntp
systemd v245.6-2.fc32 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Failed to mount /etc/machine-id: Operation not permitted
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

I also tried with ``-v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp`` and got same result.

**Comment by adelton** [comment]
What does `docker=podman tests/run-partial-tests.sh Dockerfile.fedora-32` show?

**Comment by tiran** [comment]
I'm using the image from ``docker.io/freeipa/freeipa-server`` with podman as ``root``.

The test script fails with ``can only create exec sessions on running containers: container state improper`` when I run it as regular user. Should I try it again as ``root``?
```
$ docker=podman tests/run-partial-tests.sh Dockerfile.fedora-32
STEP 1: FROM registry.fedoraproject.org/fedora:32
STEP 2: RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy
--> Using cache 4bd07a543cabcad6b1850f9547e93e8f5229f9b0492e7dc4bc71acb5c2ad5322
STEP 3: RUN groupadd -g 289 ipaapi; useradd -u 289 -g 289 -c 'IPA Framework User' -r -d / -s '/sbin/nologin' ipaapi
--> Using cache 4879cc2377237c926f553ba27560f2a9dbd5475acc81d8e128ce807ce4f46b66
STEP 4: RUN ln -s /bin/false /usr/sbin/systemd-machine-id-setup
--> Using cache 528bac98cc91c6324d6260e6f15c3ff2cea75eb557eb47317552bf65be1209a6
STEP 5: RUN dnf upgrade -y --setopt=install_weak_deps=False     && dnf install -y --setopt=install_weak_deps=False freeipa-server freeipa-server-dns freeipa-server-trust-ad patch      && dnf clean all
--> Using cache 9f11d4e0820f64fdfed3e58084d252c8cd81ab021c444d2e01bd03b1218e205d
STEP 6: RUN test $( getent passwd | grep -E "^(dirsrv:x:389|ipaapi:x:289|kdcproxy:x:288|pkiuser:x:17):" | wc -l ) -eq 4
--> Using cache bfdfcab94f49a567c32ca6768001ac6e3d0749d83569e370ca54d01108158226
STEP 7: RUN systemctl mask rpc-gssd.service
--> Using cache 06c1319962d9b0fe0a6fa349a0df07c40037b3f6ceda81be15d7ccd4ab291c6c
STEP 8: RUN test -f /etc/machine-id && ! test -s /etc/machine-id
--> Using cache b13e19e6571cc47242feabf4ffd5514834905187fd5866dc18927395a2736137
STEP 9: RUN test "$container" = oci
--> Using cache 34e76f08613c6f6e12eb0c82cc71761a1f1276a45c42b6b5714cd63d73544a3b
STEP 10: RUN echo "DefaultLimitNOFILE=1024" >> /etc/systemd/system.conf
--> Using cache e6bc40d88172183471687d8cdfa0cc34961e22ce2554a08e36d66588b3b601d3
STEP 11: ENTRYPOINT [ "/usr/sbin/init" ]
--> Using cache 8f182093ac46a7632a7e4c9e01cf567b038a3698758617555dff296629bb59ad
STEP 12: STOPSIGNAL RTMIN+3
--> Using cache 7303cedfc96ee4e9eaebbf431f22de8c3cf6255b8e2ed0079fa7e82a311a6ab1
STEP 13: RUN mkdir /var/log/journal
--> Using cache 30bca342665dbd086d63d539b5803dc8d7e508e968dbf41a21ef7a8bd01102a9
STEP 14: COMMIT local/freeipa-server-test:fedora-32
--> 30bca342665
30bca342665dbd086d63d539b5803dc8d7e508e968dbf41a21ef7a8bd01102a9
STEP 1: FROM local/freeipa-server-test:fedora-32
STEP 2: VOLUME [ "/var/log/journal" ]
--> Using cache f81e145142bb06101d39c10ec3f0307d2edf7b3864251f5ad7152ee5e7790db1
STEP 3: COMMIT local/freeipa-server-test-addons:fedora-32
--> f81e145142b
f81e145142bb06101d39c10ec3f0307d2edf7b3864251f5ad7152ee5e7790db1
bd7004bfbf08e48f2fdf5faeceadc2c65c85e42e3b731e7a2b2864507cd6d6f9
Executing tests/systemd-container-failed.sh freeipa-server-container-fedora-32
Error: can only create exec sessions on running containers: container state improper
```

**Comment by adelton** [comment]
Please pull from master and try again -- the `registry.fedoraproject.org/fedora:32` now seems to have systemd removed so I had to push the same changes we had in rawhide to the `Dockerfile.fedora-32` as well.

Whether you want to run this as root or as rootless container depends on what you try to achieve. For basic test, rootless works for me. When you want to test inter-container communication (for example testing replicas), that cannot be done with rootless out of box.

**Comment by tiran** [comment]
I'm still getting the same error at revision 323dfb052b71a361e14d9a648ab71b84a1b4c425:

```
Executing tests/systemd-container-failed.sh freeipa-server-container-fedora-32 systemd-logind.service
Error: can only create exec sessions on running containers: container state improper
```

I have cleared podman cache with ``podman rmi --all --force`` and rebuild the image from scratch. My laptop is on Fedora 32 with ``podman-2.0.2-1.fc32.x86_64`` and CGroups V2.

**Comment by adelton** [comment]
What does
```
podman run --rm -ti --read-only registry.fedoraproject.org/fedora:31 /usr/sbin/init
```
show? Do you have `container_manage_cgroup` boolean set?

**Comment by tiran** [comment]
Yes, I have the SELinux bool set:

```
# getsebool container_manage_cgroup
container_manage_cgroup --> on
```

```
$ podman run --rm -ti --read-only registry.fedoraproject.org/fedora:31 /usr/sbin/init
Trying to pull registry.fedoraproject.org/fedora:31...
Getting image source signatures
Copying blob c28ace6b0c4a done  
Copying config a7a37f74ff done  
Writing manifest to image destination
Storing signatures
systemd v243.8-1.fc31 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.

Welcome to Fedora 31 (Container Image)!

Set hostname to <ed5ad1407285>.
Initializing machine ID from random generator.
Failed to mount /etc/machine-id: Operation not permitted
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target Local File Systems.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Reached target Slices.
[  OK  ] Reached target Swap.
[  OK  ] Listening on Process Core Dump Socket.
[  OK  ] Listening on initctl Compatibility Named Pipe.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Listening on Journal Socket.
         Starting Journal Service...
[  OK  ] Started Journal Service.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Started Flush Journal to Persistent Storage.
         Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Timers.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Reached target Basic System.
         Starting Permit User Sessions...
[  OK  ] Started Permit User Sessions.
[  OK  ] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.
```

**Comment by adelton** [comment]
Hmmm. And what does
```
podman run --rm -ti 30bca342665dbd086d63d539b5803dc8d7e508e968dbf41a21ef7a8bd01102a9
```
output?

**Comment by tiran** [comment]
``Error: invalid image reference "30bca342665dbd086d63d539b5803dc8d7e508e968dbf41a21ef7a8bd01102a9"``
Is that an older F32 container?

**Comment by adelton** [comment]
No, that's the image you've built:
```
STEP 13: RUN mkdir /var/log/journal
--> Using cache 30bca342665dbd086d63d539b5803dc8d7e508e968dbf41a21ef7a8bd01102a9
STEP 14: COMMIT local/freeipa-server-test:fedora-32
--> 30bca342665
30bca342665dbd086d63d539b5803dc8d7e508e968dbf41a21ef7a8bd01102a9
```

**Comment by adelton** [comment]
Ahh, you've removed them all.
Just rerun the `docker=podman tests/run-partial-tests.sh Dockerfile.fedora-32` and then run `podman run --rm -ti` on the last image you've got, to see what systemd spits out.

**Comment by adelton** [comment]
Alright, so I've noticed that you use podman 2.0 while I was at 1.9.3-1.fc32. So I've upgraded to 2.0.2-1.fc32 and now I see
```
$ podman run --rm -ti 34b9d142b368076f4df1faa1b35f15e00e96bf9f24c72b90d6959fa4e105cde6
Failed to mount tmpfs at /run: Operation not permitted
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...
```
What is strange to me is that even the registry.fedoraproject.org/fedora:31 systemd container now does not seem to run:
```
$ podman run --rm -ti --read-only registry.fedoraproject.org/fedora:31 /usr/sbin/init
systemd v243.8-1.fc31 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
Detected virtualization podman.
Detected architecture x86-64.

Welcome to Fedora 31 (Container Image)!

Set hostname to <65254a037007>.
Initializing machine ID from random generator.
Failed to mount /etc/machine-id: Operation not permitted
Failed to create /user.slice/user-1000.slice/session-3.scope/init.scope control group: Permission denied
Failed to allocate manager object: Permission denied
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```
It's a clear regression so you might want to downgrade to podman 1.9.3 before we figure out how to report that to the podman team.

**Comment by adelton** [comment]
I've now filed https://bugzilla.redhat.com/show_bug.cgi?id=1856396 for the Fedora 31 systemd container failing. What I don't fully understand is why it works on your box. Do you use systemd.unified_cgroup_hierarchy=0 or cgroups v2?

**Comment by tiran** [comment]
I'm using cgroups v2. I removed ``systemd.unified_cgroup_hierarchy=0`` shortly after I upgraded to F32.

Let me downgrade podman and see if I can get the image working with 1.9.x.

**Comment by adelton** [comment]
@tiran Were you able to get the `tests/run-partial-tests.sh` running with podman 1.8?

**Comment by adelton** [comment]
@tiran Can we get some closure to this issue? Were you able to get things running with rootless podman 1.8 or rootful podman or with docker?

**Comment by adelton** [comment]
We seem to have lost traction here.
