### ISSUE TITLE
IPA installation fails to configure CA instance 

### ISSUE THREAD

**Issue by juanheliosg** [freeipa/freeipa-container#372]
Hi, i can't install IPA from centos-8 images due to a fail in CA configuration.

This is ipaserver-install.log fail:
2021-01-28T23:00:14Z CRITICAL Failed to configure CA instance: CalledProcessError(Command ['/usr/sbin/pkispawn', '-s', 'CA', '-f', '/tmp/tmpxx7w_cyq', '--debug'] returned non-zero exit status 1: 'Traceback (most recent call last):\n  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/usr/lib/python3.9/site-packages/pki/server/pkispawn.py", line 936, in <module>\n    main(sys.argv)\n  File "/usr/lib/python3.9/site-packages/pki/server/pkispawn.py", line 545, in main\n    pkilogging.enable_pki_logger(log_file, \'pkispawn\')\n  File "/usr/lib/python3.9/site-packages/pki/server/deployment/pkilogging.py", line 55, in enable_pki_logger\n    log_file = logging.FileHandler(filename, \'w\')\n  File "/usr/lib64/python3.9/logging/__init__.py", line 1142, in __init__\n    StreamHandler.__init__(self, self._open())\n  File "/usr/lib64/python3.9/logging/__init__.py", line 1171, in _open\n    return open(self.baseFilename, self.mode, encoding=self.encoding,\nFileNotFoundError: [Errno 2] No such file or directory: \'/var/log/pki/pki-ca-spawn.20210128230013.log\'\n')

**Comment by adelton** [comment]
How did you resolve the issue?

**Comment by juanheliosg** [comment]
I had a wrong volume in my docker-compose which was interfering with /var/logs . Removing that volume which was not needed for the installation solved the issue
