### ISSUE TITLE
Docker run ipa-server-install centos7

### ISSUE THREAD

**Issue by guillermocol** [freeipa/freeipa-container#395]
Hello team,

I am trying to run a docker container in a centos7 server, but once the docker container is created and I run the command: 

ipa-server-install --no-ntp

I get the following error:

ipapython.admintool: ERROR    IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
ipapython.admintool: ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

Running ifconfig, the docker service has assigned an eth0 an lo network interface.

Thank you for your help,

**Comment by guillermocol** [comment]
I got it solved, but now I get:  it could be a bug? 
2021-04-19T11:29:06Z DEBUG The ipa-server-install command failed, exception: RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2Qw2HX' returned non-zero exit status 1
2021-04-19T11:29:06Z ERROR failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2Qw2HX' returned non-zero exit status 1
2021-04-19T11:29:06Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

**Comment by zwets** [comment]
Take a look in the README. The error message and its solution are documented there.

**Comment by guillermocol** [comment]
I was able to solve the first error with 

{
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
}

in /etc/docker/daemon.json

but the second error that I posted, I am not able to find out from where is coming. Do you think is also related? 
that one appears after introducing details as domain, the passwords for the installation, etc. During the installation in step 1 fails.
Before changing the daemon.json was giving the first error.
If I try what README suggests from the beginning during the docker run, I get this message:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "--sysctl": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 

Thank you for you help zwets

**Comment by guillermocol** [comment]
I think one reason can be the ipa version is too old for this docker container.
version 4.6.8
It can be the reason... what version of ipa is recommended to have installed with centos 7 docker service? :/

Thank you

**Comment by adelton** [comment]
Run the container for example with `-e DEBUG_NO_EXIT=1` and then `docker exec` into the container and check the `/var/log/ipaserver-install.log` and the journal (with `journalctl`).

Please also state the exact version of the OS and docker on the host, and the exact `docker run` command that you used.

**Comment by adelton** [comment]
> I think one reason can be the ipa version is too old for this docker container.
> version 4.6.8
> It can be the reason... what version of ipa is recommended to have installed with centos 7 docker service? :/

The latest IPA version as packaged in CentOS 7 is ipa-server-4.6.8-5.el7.centos.x86_64.rpm as shown at http://mirror.centos.org/centos/7/os/x86_64/Packages/, and that's the version which gets installed and packaged to https://hub.docker.com/r/freeipa/freeipa-server/tags?page=1&ordering=last_updated&name=centos-7.

**Comment by guillermocol** [comment]
Thank you Adelton, then I am downloading the latest 4.6.8 
The exact OS on the host Amazon Linux 2 and in Docker service CentOS7
The /var/log/ipaserver-install.log shows the following message:

  File "/usr/lib/python2.7/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/__init__.py", line 590, in main
    master_install(self)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 250, in decorated
    func(installer)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 783, in install
    setup_pkinit=not options.no_pkinit)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 346, in create_instance
    self.start_creation(runtime=30)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 567, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 557, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 587, in __create_instance
    raise RuntimeError("failed to create DS instance %s" % e)

2021-04-19T14:22:09Z DEBUG The ipa-server-install command failed, exception: RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp1tIJBK' returned non-zero exit status 1
2021-04-19T14:22:09Z ERROR failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp1tIJBK' returned non-zero exit status 1
2021-04-19T14:22:09Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information


journalctl shows the following message:

journalctl
No journal files were found.

Thank you for your help

**Comment by adelton** [comment]
What does "in Docker service CentOS7" mean?

We will need longer output from the `ipaserver-install.log` to see what's before those last lines of traceback.

What is your exact purpose of attempting to run FreeIPA there in a container rather than installing it directly on that Amazon Linux host? Isn't `ipa-server` available in Amazon Linux repositories?

**Comment by adelton** [comment]
By the way, in https://github.com/freeipa/freeipa-container/issues/391 you've said that you already got to a point of "FreeIPA server started". How is what you are doing now different from what you were attempting to do there? Does `tests/run-partial-tests.sh` work on this host?

**Comment by guillermocol** [comment]
I was able to run it in Amazon linux 2 host successfully and in my local machine using docker in #391 but running docker in amazon linux 2 and debian server I get these errors.

**Comment by adelton** [comment]
I'm sorry, you seem to only answer half of my questions. I'm unable to help you.

**Comment by guillermocol** [comment]
- The Docker service runs in Centos 7 and the host is amzn linux2
- I think it is available in amzn repositories 
- The command: 

 docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 --env oci-systemd-hook=disabled -ti -h host.test.com
-v /sys/fs/cgroup:/sys/fs/cgroup:ro
-v /var/lib/ipa-data:/data:Z

-  The logs I get: ipaserver-install.log

2021-04-19T15:57:08Z DEBUG calling setup-ds.pl
2021-04-19T15:57:08Z DEBUG Starting external process
2021-04-19T15:57:08Z DEBUG args=/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4
2021-04-19T15:57:11Z DEBUG Process finished, return code=1
2021-04-19T15:57:11Z DEBUG stdout=[21/04/19:15:57:11] - [Setup] Info Error: command '/bin/systemctl --system daemon-reload' failed - output [Failed to get D-Bus connection: Operation not permitted
] error []Error: command '/bin/systemctl --system daemon-reload' failed - output [Failed to get D-Bus connection: Operation not permitted
] error [][21/04/19:15:57:11] - [Setup] Fatal Error: Could not create directory server instance 'TEST-COM'.
Error: Could not create directory server instance 'TEST-COM'.
[21/04/19:15:57:11] - [Setup] Fatal Exiting . . .
Log file is '-'

Exiting . . .
Log file is '-'


2021-04-19T15:57:11Z DEBUG stderr=
2021-04-19T15:57:11Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 567, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 557, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 587, in __create_instance
    raise RuntimeError("failed to create DS instance %s" % e)
RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1

2021-04-19T15:57:11Z DEBUG   [error] RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1
2021-04-19T15:57:11Z DEBUG   File "/usr/lib/python2.7/site-packages/ipapython/admintool.py", line 178, in execute
    return_value = self.run()
  File "/usr/lib/python2.7/site-packages/ipapython/install/cli.py", line 319, in run
    return cfgr.run()
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python2.7/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/__init__.py", line 590, in main
    master_install(self)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 250, in decorated
    func(installer)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 783, in install
    setup_pkinit=not options.no_pkinit)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 346, in create_instance
    self.start_creation(runtime=30)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 567, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 557, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 587, in __create_instance
    raise RuntimeError("failed to create DS instance %s" % e)

2021-04-19T15:57:11Z DEBUG The ipa-server-install command failed, exception: RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1
2021-04-19T15:57:11Z ERROR failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1
2021-04-19T15:57:11Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
