### ISSUE TITLE
Running Docker service CentOS 7 continuation #395

### ISSUE THREAD

**Issue by guillermocol** [freeipa/freeipa-container#396]
Hello team,

Sorry for not answering all the questions in detail, here are all the details about the issue:

I am trying to run a docker container in a centos7 server, but once the docker container is created and I run the command: 

ipa-server-install --no-ntp

I get the following error:

ipapython.admintool: ERROR    IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
ipapython.admintool: ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

Running ifconfig, the docker service has assigned an eth0 an lo network interface.

The Docker service runs in Centos 7 and the host is amzn linux2
I think it is available in amzn repositories
The command:
docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 --env oci-systemd-hook=disabled -ti -h host.test.com
-v /sys/fs/cgroup:/sys/fs/cgroup:ro
-v /var/lib/ipa-data:/data:Z

The logs I get: ipaserver-install.log
2021-04-19T15:57:08Z DEBUG calling setup-ds.pl
2021-04-19T15:57:08Z DEBUG Starting external process
2021-04-19T15:57:08Z DEBUG args=/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4
2021-04-19T15:57:11Z DEBUG Process finished, return code=1
2021-04-19T15:57:11Z DEBUG stdout=[21/04/19:15:57:11] - [Setup] Info Error: command '/bin/systemctl --system daemon-reload' failed - output [Failed to get D-Bus connection: Operation not permitted
] error []Error: command '/bin/systemctl --system daemon-reload' failed - output [Failed to get D-Bus connection: Operation not permitted
] error [][21/04/19:15:57:11] - [Setup] Fatal Error: Could not create directory server instance 'TEST-COM'.
Error: Could not create directory server instance 'TEST-COM'.
[21/04/19:15:57:11] - [Setup] Fatal Exiting . . .
Log file is '-'

Exiting . . .
Log file is '-'

2021-04-19T15:57:11Z DEBUG stderr=
2021-04-19T15:57:11Z DEBUG Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 567, in start_creation
run_step(full_msg, method)
File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 557, in run_step
method()
File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 587, in __create_instance
raise RuntimeError("failed to create DS instance %s" % e)
RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1

2021-04-19T15:57:11Z DEBUG [error] RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1
2021-04-19T15:57:11Z DEBUG File "/usr/lib/python2.7/site-packages/ipapython/admintool.py", line 178, in execute
return_value = self.run()
File "/usr/lib/python2.7/site-packages/ipapython/install/cli.py", line 319, in run
return cfgr.run()
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 360, in run
return self.execute()
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 386, in execute
for rval in self._executor():
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 431, in __runner
exc_handler(exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
self._handle_exception(exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
six.reraise(*exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 421, in __runner
step()
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 418, in
step = lambda: next(self.__gen)
File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
six.reraise(*exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
value = gen.send(prev_value)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 655, in _configure
next(executor)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 431, in __runner
exc_handler(exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
self._handle_exception(exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 518, in _handle_exception
self.__parent._handle_exception(exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
six.reraise(*exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 515, in _handle_exception
super(ComponentBase, self)._handle_exception(exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
six.reraise(*exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 421, in __runner
step()
File "/usr/lib/python2.7/site-packages/ipapython/install/core.py", line 418, in
step = lambda: next(self.__gen)
File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
six.reraise(*exc_info)
File "/usr/lib/python2.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
value = gen.send(prev_value)
File "/usr/lib/python2.7/site-packages/ipapython/install/common.py", line 65, in _install
for unused in self._installer(self.parent):
File "/usr/lib/python2.7/site-packages/ipaserver/install/server/init.py", line 590, in main
master_install(self)
File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 250, in decorated
func(installer)
File "/usr/lib/python2.7/site-packages/ipaserver/install/server/install.py", line 783, in install
setup_pkinit=not options.no_pkinit)
File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 346, in create_instance
self.start_creation(runtime=30)
File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 567, in start_creation
run_step(full_msg, method)
File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 557, in run_step
method()
File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 587, in __create_instance
raise RuntimeError("failed to create DS instance %s" % e)

2021-04-19T15:57:11Z DEBUG The ipa-server-install command failed, exception: RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1
2021-04-19T15:57:11Z ERROR failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2VEhz4' returned non-zero exit status 1
2021-04-19T15:57:11Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

Thank you for your help,

**Comment by guillermocol** [comment]
I managed to solve it . Thank you

**Comment by adelton** [comment]
Could you share the root cause and the fix?

**Comment by guillermocol** [comment]
I didn't manage to use a server with Debian and a docker service with centos. I used a centos server and a docker service in CentOS and it worked out.
