### ISSUE TITLE
ipa-server-install: systemd fails to start dirsrv

### ISSUE THREAD

**Issue by eboddington** [freeipa/freeipa-container#449]
Running the following command:
`docker run --rm -ti -h ipa.mydomain.com -v "/sys/fs/cgroup:/sys/fs/cgroup:ro" -v /share/AppData/freeipa:/data:Z --read-only --sysctl net.ipv6.conf.all.disable_ipv6=0 -e PASSWORD=Secret123 freeipa/freeipa-server:centos-8-stream ipa-server-install -U --skip-mem-check -r ipa.mydomain.com -n ipa.mydomain.com --no-ntp`

fails with:
```
Disabled p11-kit-proxy
Configuring directory server (dirsrv). Estimated time: 30 seconds
  [1/41]: creating directory server instance
Validate installation settings ...
Create file system structures ...
Perform SELinux labeling ...
  [error] CalledProcessError: Command '['systemctl', 'start', 'dirsrv@IPA-MYDOMAIN-COM']' returned non-zero exit status 1.
Command '['systemctl', 'start', 'dirsrv@IPA-MYDOMAIN-COM']' returned non-zero exit status 1.
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

I've tried searching for similar issues, but nothing has pointed me to any fixes. What should I try?

**Comment by adelton** [comment]
What can be found in `/share/AppData/freeipa/var/log/ipaserver-install.log`?

**Comment by eboddington** [comment]
> What can be found in `/share/AppData/freeipa/var/log/ipaserver-install.log`?

Not sure what might be useful, so I've included the whole thing, I didn't see anything which gave me any clues 😄 
```
2022-04-05T17:30:30Z DEBUG Logging to /var/log/ipaserver-install.log
2022-04-05T17:30:30Z DEBUG ipa-server-install was invoked with arguments [] and options: {'unattended': True, 'ip_addresses': None, 'domain_name': 'ipa.mydomain.com', 'realm_name': 'IPA.MYDOMAIN.COM', 'host_name': None, 'ca_cert_files': None, 'domain_level': None, 'setup_adtrust': False, 'setup_kra': False, 'setup_dns': False, 'idstart': None, 'idmax': None, 'no_hbac_allow': False, 'no_pkinit': False, 'no_ui_redirect': False, 'dirsrv_config_file': None, 'skip_mem_check': True, 'dirsrv_cert_files': None, 'http_cert_files': None, 'pkinit_cert_files': None, 'dirsrv_cert_name': None, 'http_cert_name': None, 'pkinit_cert_name': None, 'mkhomedir': False, 'ntp_servers': None, 'ntp_pool': None, 'no_ntp': True, 'force_ntpd': False, 'ssh_trust_dns': False, 'no_ssh': False, 'no_sshd': False, 'no_dns_sshfp': False, 'external_ca': False, 'external_ca_type': None, 'external_ca_profile': None, 'external_cert_files': None, 'subject_base': None, 'ca_subject': None, 'ca_signing_algorithm': None, 'pki_config_override': None, 'allow_zone_overlap': False, 'reverse_zones': None, 'no_reverse': False, 'auto_reverse': False, 'zonemgr': None, 'forwarders': None, 'no_forwarders': False, 'auto_forwarders': False, 'forward_policy': None, 'no_dnssec_validation': False, 'no_host_dns': False, 'enable_compat': False, 'no_msdcs': False, 'netbios_name': None, 'rid_base': None, 'secondary_rid_base': None, 'ignore_topology_disconnect': False, 'ignore_last_of_role': False, 'verbose': False, 'quiet': False, 'log_file': None, 'uninstall': False}
2022-04-05T17:30:30Z DEBUG IPA version 4.9.8-7.module_el8.6.0+1103+a004f6a8
2022-04-05T17:30:30Z DEBUG IPA platform rhel_container
2022-04-05T17:30:30Z DEBUG IPA os-release CentOS Stream 8
2022-04-05T17:30:30Z DEBUG Searching for an interface of IP address: ::1
2022-04-05T17:30:30Z DEBUG Testing local IP address: ::1/128 (interface: lo)
2022-04-05T17:30:30Z DEBUG Starting external process
2022-04-05T17:30:30Z DEBUG args=['/usr/sbin/selinuxenabled']
2022-04-05T17:30:30Z DEBUG Process finished, return code=1
2022-04-05T17:30:30Z DEBUG stdout=
2022-04-05T17:30:30Z DEBUG stderr=
2022-04-05T17:30:30Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2022-04-05T17:30:30Z DEBUG Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
2022-04-05T17:30:30Z DEBUG httpd is not configured
2022-04-05T17:30:30Z DEBUG kadmin is not configured
2022-04-05T17:30:30Z DEBUG dirsrv is not configured
2022-04-05T17:30:30Z DEBUG pki-tomcatd is not configured
2022-04-05T17:30:30Z DEBUG install is not configured
2022-04-05T17:30:30Z DEBUG krb5kdc is not configured
2022-04-05T17:30:30Z DEBUG named is not configured
2022-04-05T17:30:30Z DEBUG filestore is tracking no files
2022-04-05T17:30:30Z DEBUG Loading Index file from '/var/lib/ipa-client/sysrestore/sysrestore.index'
2022-04-05T17:30:30Z DEBUG Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
2022-04-05T17:30:30Z DEBUG Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
2022-04-05T17:30:30Z DEBUG Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
2022-04-05T17:30:30Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2022-04-05T17:30:30Z DEBUG Check if ipa.mydomain.com is a primary hostname for localhost
2022-04-05T17:30:30Z DEBUG Primary hostname for localhost: ipa.mydomain.com
2022-04-05T17:30:30Z DEBUG Search DNS for ipa.mydomain.com
2022-04-05T17:30:30Z DEBUG Check if ipa.mydomain.com is not a CNAME
2022-04-05T17:30:30Z DEBUG Check reverse address of 10.0.3.2
2022-04-05T17:30:30Z DEBUG Found reverse name: ipa.mydomain.com
2022-04-05T17:30:30Z DEBUG will use host_name: ipa.mydomain.com

2022-04-05T17:30:30Z DEBUG Writing configuration file /etc/ipa/default.conf
2022-04-05T17:30:30Z DEBUG [global]
host = ipa.mydomain.com
basedn = dc=ipa,dc=mydomain,dc=com
realm = IPA.MYDOMAIN.COM
domain = ipa.mydomain.com
xmlrpc_uri = https://ipa.mydomain.com/ipa/xml
ldap_uri = ldapi://%2Frun%2Fslapd-IPA-MYDOMAIN-COM.socket
mode = production
enable_ra = True
ra_plugin = dogtag
dogtag_version = 10



2022-04-05T17:30:30Z DEBUG importing all plugin modules in ipaserver.plugins...
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.aci
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.automember
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.automount
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.baseldap
2022-04-05T17:30:30Z DEBUG ipaserver.plugins.baseldap is not a valid plugin module
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.baseuser
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.batch
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.ca
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.caacl
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.cert
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.certmap
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.certprofile
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.config
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.delegation
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.dns
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.dnsserver
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.dogtag
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.domainlevel
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.group
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.hbac
2022-04-05T17:30:30Z DEBUG ipaserver.plugins.hbac is not a valid plugin module
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.hbacrule
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.hbacsvc
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.hbacsvcgroup
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.hbactest
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.host
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.hostgroup
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.idrange
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.idviews
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.internal
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.join
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.krbtpolicy
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.ldap2
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.location
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.migration
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.misc
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.netgroup
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.otp
2022-04-05T17:30:30Z DEBUG ipaserver.plugins.otp is not a valid plugin module
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.otpconfig
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.otptoken
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.passwd
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.permission
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.ping
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.pkinit
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.privilege
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.pwpolicy
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.rabase
2022-04-05T17:30:30Z DEBUG ipaserver.plugins.rabase is not a valid plugin module
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.radiusproxy
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.realmdomains
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.role
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.schema
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.selfservice
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.selinuxusermap
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.server
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.serverrole
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.serverroles
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.service
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.servicedelegation
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.session
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.stageuser
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.subid
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.sudo
2022-04-05T17:30:30Z DEBUG ipaserver.plugins.sudo is not a valid plugin module
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.sudocmd
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.sudocmdgroup
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.sudorule
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.topology
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.trust
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.user
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.vault
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.virtual
2022-04-05T17:30:30Z DEBUG ipaserver.plugins.virtual is not a valid plugin module
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.whoami
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.plugins.xmlserver
2022-04-05T17:30:30Z DEBUG importing all plugin modules in ipaserver.install.plugins...
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.adtrust
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.ca_renewal_master
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.dns
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.fix_kra_people_entry
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.fix_replica_agreements
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.rename_managed
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_ca_topology
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_changelog_maxage
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_dna_shared_config
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_fix_duplicate_cacrt_in_ldap
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_idranges
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_ldap_server_list
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_managed_permissions
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_nis
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_pacs
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_passsync
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_pwpolicy
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_ra_cert_store
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_referint
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_services
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_unhashed_password
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.update_uniqueness
2022-04-05T17:30:30Z DEBUG importing plugin module ipaserver.install.plugins.upload_cacrt
2022-04-05T17:30:32Z DEBUG check_port_bindable: Checking IPv4/IPv6 dual stack and TCP
2022-04-05T17:30:32Z DEBUG check_port_bindable: bind success: 8443/TCP
2022-04-05T17:30:32Z DEBUG check_port_bindable: Checking IPv4/IPv6 dual stack and TCP
2022-04-05T17:30:32Z DEBUG check_port_bindable: bind success: 8080/TCP
2022-04-05T17:30:32Z DEBUG Name ipa.mydomain.com resolved to {UnsafeIPAddress('10.0.3.2')}
2022-04-05T17:30:32Z DEBUG Searching for an interface of IP address: 10.0.3.2
2022-04-05T17:30:32Z DEBUG Testing local IP address: 127.0.0.1/255.0.0.0 (interface: lo)
2022-04-05T17:30:32Z DEBUG Testing local IP address: 10.0.3.2/255.255.255.0 (interface: eth0)
2022-04-05T17:30:32Z DEBUG LDAP is not connected, can not retrieve NetBIOS name
2022-04-05T17:30:32Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2022-04-05T17:30:32Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2022-04-05T17:30:32Z DEBUG Starting external process
2022-04-05T17:30:32Z DEBUG args=['/usr/sbin/selinuxenabled']
2022-04-05T17:30:32Z DEBUG Process finished, return code=1
2022-04-05T17:30:32Z DEBUG stdout=
2022-04-05T17:30:32Z DEBUG stderr=
2022-04-05T17:30:32Z DEBUG Created PKCS#11 module config '/etc/pkcs11/modules/softhsm2.module'.
2022-04-05T17:30:32Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2022-04-05T17:30:32Z DEBUG Configuring directory server (dirsrv). Estimated time: 30 seconds
2022-04-05T17:30:32Z DEBUG   [1/41]: creating directory server instance
2022-04-05T17:30:32Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2022-04-05T17:30:32Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2022-04-05T17:30:32Z DEBUG Running setup with verbose
2022-04-05T17:30:32Z DEBUG START: Starting installation ...
2022-04-05T17:30:32Z DEBUG READY: Preparing installation for IPA-MYDOMAIN-COM...
2022-04-05T17:30:32Z INFO Validate installation settings ...
2022-04-05T17:30:32Z DEBUG PASSED: using config settings 999999999
2022-04-05T17:30:32Z DEBUG PASSED: user / group checking
2022-04-05T17:30:32Z DEBUG PASSED: prefix checking
2022-04-05T17:30:32Z DEBUG list instance not found in /etc/dirsrv/slapd-IPA-MYDOMAIN-COM/dse.ldif: IPA-MYDOMAIN-COM

2022-04-05T17:30:32Z DEBUG PASSED: instance checking
2022-04-05T17:30:32Z DEBUG INFO: temp root password set to ssQpkZ.LWjQH.4rtTBnKfqg2p3WIQrcAbEhiUTATlVESMVM8aDQd6ToSTgHz6DwDz
2022-04-05T17:30:32Z DEBUG PASSED: root user checking
2022-04-05T17:30:32Z DEBUG PASSED: network avaliability checking
2022-04-05T17:30:32Z DEBUG READY: Beginning installation for IPA-MYDOMAIN-COM...
2022-04-05T17:30:32Z DEBUG ACTION: Creating dse.ldif
2022-04-05T17:30:32Z DEBUG Container detected setting db home directory to db directory.
2022-04-05T17:30:32Z INFO Create file system structures ...
2022-04-05T17:30:32Z DEBUG ACTION: creating /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/bak
2022-04-05T17:30:32Z DEBUG ACTION: creating /etc/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:32Z DEBUG ACTION: creating /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/db
2022-04-05T17:30:32Z DEBUG ACTION: creating /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/db
2022-04-05T17:30:32Z DEBUG ACTION: creating /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/ldif
2022-04-05T17:30:32Z DEBUG ACTION: creating /run/lock/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:32Z DEBUG ACTION: creating /var/log/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:32Z DEBUG ACTION: creating /run/dirsrv
2022-04-05T17:30:33Z DEBUG b'CMD: systemctl enable dirsrv@IPA-MYDOMAIN-COM ; STDOUT:  ; STDERR: Created symlink /etc/systemd/system/multi-user.target.wants/dirsrv@IPA-MYDOMAIN-COM.service \xe2\x86\x92 /usr/lib/systemd/system/dirsrv@.service.\n'
2022-04-05T17:30:33Z DEBUG ACTION: Creating certificate database is /etc/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:33Z DEBUG Allocate <class 'lib389.DirSrv'> with None
2022-04-05T17:30:33Z DEBUG Allocate <class 'lib389.DirSrv'> with /run/slapd-IPA-MYDOMAIN-COM.socket
2022-04-05T17:30:33Z DEBUG Allocate <class 'lib389.DirSrv'> with localhost:389
2022-04-05T17:30:33Z DEBUG Allocate <class 'lib389.DirSrv'> with localhost:389
2022-04-05T17:30:33Z DEBUG nss cmd: /usr/bin/certutil -N -d /etc/dirsrv/slapd-IPA-MYDOMAIN-COM -f /etc/dirsrv/slapd-IPA-MYDOMAIN-COM/pwdfile.txt
2022-04-05T17:30:33Z DEBUG nss output:
2022-04-05T17:30:33Z INFO Perform SELinux labeling ...
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/bak
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /etc/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /etc/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/db
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/ldif
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /run/lock/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /var/log/dirsrv/slapd-IPA-MYDOMAIN-COM
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /var/lib/dirsrv/slapd-IPA-MYDOMAIN-COM/db
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /run/dirsrv
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /etc/dirsrv/slapd-IPA-MYDOMAIN-COM/schema
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping relabel path /tmp
2022-04-05T17:30:33Z DEBUG selinux is disabled, skipping port relabel
2022-04-05T17:30:33Z DEBUG systemd status -> True
2022-04-05T17:30:33Z DEBUG systemd status -> True
2022-04-05T17:30:33Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 635, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 621, in run_step
    method()
  File "/usr/lib/python3.6/site-packages/ipaserver/install/dsinstance.py", line 553, in __create_instance
    sds.create_from_args(general, slapd, backends, None)
  File "/usr/lib/python3.6/site-packages/lib389/instance/setup.py", line 674, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.6/site-packages/lib389/instance/setup.py", line 921, in _install_ds
    ds_instance.start(timeout=60)
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 1147, in start
    subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemctl', 'start', 'dirsrv@IPA-MYDOMAIN-COM']' returned non-zero exit status 1.

2022-04-05T17:30:33Z DEBUG   [error] CalledProcessError: Command '['systemctl', 'start', 'dirsrv@IPA-MYDOMAIN-COM']' returned non-zero exit status 1.
2022-04-05T17:30:33Z DEBUG   File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 342, in run
    return cfgr.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/__init__.py", line 570, in main
    master_install(self)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 275, in decorated
    func(installer)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 869, in install
    setup_pkinit=not options.no_pkinit)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/dsinstance.py", line 322, in create_instance
    self.start_creation(runtime=30)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 635, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 621, in run_step
    method()
  File "/usr/lib/python3.6/site-packages/ipaserver/install/dsinstance.py", line 553, in __create_instance
    sds.create_from_args(general, slapd, backends, None)
  File "/usr/lib/python3.6/site-packages/lib389/instance/setup.py", line 674, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.6/site-packages/lib389/instance/setup.py", line 921, in _install_ds
    ds_instance.start(timeout=60)
  File "/usr/lib/python3.6/site-packages/lib389/__init__.py", line 1147, in start
    subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)

2022-04-05T17:30:33Z DEBUG The ipa-server-install command failed, exception: CalledProcessError: Command '['systemctl', 'start', 'dirsrv@IPA-MYDOMAIN-COM']' returned non-zero exit status 1.
2022-04-05T17:30:33Z ERROR Command '['systemctl', 'start', 'dirsrv@IPA-MYDOMAIN-COM']' returned non-zero exit status 1.
2022-04-05T17:30:33Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

**Comment by rcritten** [comment]
/share/AppData/freeipa/var/log/dirsrv/slapd-IPA-MYDOMAIN-COM/errors is likely to contain more specific to why it wouldn't start. That and/or the journal.

**Comment by rcritten** [comment]
journalctl --file /path/to/journal should do it.

**Comment by eboddington** [comment]
> journalctl --file /path/to/journal should do it.

Ah, thanks, it did.

So, notably I see a lot of permission issues in the journal, here's a snippet (much of it seems to be the same messages repeated, so I didn't think including the whole thing would be helpful):
```
Apr 05 17:30:28 ipa.example.com systemd[1]: systemd-journald.service: Failed to add fd to store: Operation not permitted
Apr 05 17:30:28 ipa.example.com dbus-daemon[277]: [system] org.freedesktop.DBus.Error.AccessDenied: Failed to set fd limit to 65536: Operation not permitted
Apr 05 17:30:32 ipa.example.com systemd[1]: Reloading.
Apr 05 17:30:33 ipa.example.com systemd[1]: Created slice system-dirsrv.slice.
Apr 05 17:30:33 ipa.example.com systemd[1]: Starting 389 Directory Server IPA-EXAMPLE-COM....
Apr 05 17:30:33 ipa.example.com ds_systemd_ask_password_acl[319]: setfacl: /var/run/systemd/ask-password: Operation not supported
Apr 05 17:30:33 ipa.example.com systemd[1]: dirsrv@IPA-EXAMPLE-COM.service: Control process exited, code=exited status=1
Apr 05 17:30:33 ipa.example.com systemd[1]: dirsrv@IPA-EXAMPLE-COM.service: Failed with result 'exit-code'.
Apr 05 17:30:33 ipa.example.com systemd[1]: Failed to start 389 Directory Server IPA-EXAMPLE-COM..
Apr 05 17:30:33 ipa.example.com systemd[1]: ipa-server-configure-first.service: Main process exited, code=exited, status=123/n/a
Apr 05 17:30:33 ipa.example.com systemd[1]: ipa-server-configure-first.service: Failed with result 'exit-code'.
Apr 05 17:30:33 ipa.example.com systemd[1]: Failed to start Configure IPA server upon the first start.
```

I wonder if it's to do with running with a read-only filesystem? Although, this seems to be recommended. Is there anything obvious I might be missing?

**Comment by adelton** [comment]
The problem seems to be caused by the filesystem mounted to `/run` -- that `/var/run` is a link to `/run` and the image has
```
VOLUME [ "/tmp", "/run", "/data", "/var/log/journal" ]
```

What host OS? You might try to add `--tmpfs /run` or something similar to `docker run` ... or use OS that seems to be more Linux-friendly.

**Comment by eboddington** [comment]
Hmm, interesting. It's running on a QNAP NAS which is not ideal, but my only option at the moment. Adding `--tmpfs /run` worked though, thanks! I'll close this now as I've been able to successfully run the installer now.
