### ISSUE TITLE
simple bind failed error when try to use ldaps

### ISSUE THREAD

**Issue by lordk911** [freeipa/freeipa-container#453]
I install freeipa-server using docker : 
docker run --name freeipa-server --sysctl net.ipv6.conf.all.disable_ipv6=0 -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp -p 123:123/udp -ti -h freeipa.glodonpoc.com -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v /var/lib/ipa-data:/data:Z --restart=on-failure:3 freeipa-server

the image I build from source : 
docker build -t freeipa-server -f [Dockerfile.centos-7](https://github.com/freeipa/freeipa-container/blob/master/Dockerfile.centos-7) .

I'm trying to connect to freeipa server from remote by using java(1.8) with ldap[s] 
I can use ldap protocol connected to freeipa server successfully , but failed with ldaps

my test code like this: 
```
System.setProperty("javax.net.ssl.trustStore", "/Users/shin/client.truststore.jks");
System.setProperty("javax.net.ssl.trustStorePassword", "12345678.");
System.setProperty("jdk.tls.client.protocols", "TLSv1,TLSv1.1,TLSv1.2,TLSv1.3");
Hashtable env = new Hashtable<String, String>();
env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
env.put(Context.PROVIDER_URL, "ldaps://10.0.68.165:636");// LDAP server
env.put(Context.SECURITY_AUTHENTICATION, "simple");
env.put(Context.SECURITY_PRINCIPAL, "uid=" + "test" + ",cn=users,cn=accounts,dc=glodonpoc,dc=com");
env.put(Context.SECURITY_CREDENTIALS, "12345678.");
env.put(Context.SECURITY_PROTOCOL, "tls");
DirContext ctx = new InitialDirContext(env);
```
I have import the /etc/ipa/ca.crt file into the  /Users/shin/client.truststore.jks

and I got ERROR : 

```
javax.naming.CommunicationException: simple bind failed: 10.0.68.165:636 [Root exception is java.net.SocketException: Connection or outbound has closed]
	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:219)
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2895)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:694)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
......
Caused by: java.net.SocketException: Connection or outbound has closed
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1110)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.sun.jndi.ldap.Connection.writeRequest(Connection.java:450)
	at com.sun.jndi.ldap.Connection.writeRequest(Connection.java:423)
	at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:359)
	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214)
	... 13 more
```
I don't know what to do next.

**Comment by lordk911** [comment]
the host name should be used when use ldaps protocol
