### ISSUE TITLE
FIPS Support

### ISSUE THREAD

**Issue by ccravens** [freeipa/freeipa-container#483]
Hello!

We've built a base CentOS 8 stream base image with FIPS and we build FreeIPA from that base image and run on a host OS with FIPS enabled as well.

It seems that FreeIPA has support for FIPS, however it seems like it puts the system into a bit of "unknown territory": https://www.freeipa.org/page/V4/FreeIPA-on-FIPS / https://www.freeipa.org/page/V4/Replace_NSS_with_OpenSSL

I wanted to see if this is something that has been attempted with the container version of FreeIPA. The installation of FreeIPA on first start of the container produces thousands of lines of logs. However it fails at this point:

```
[root@a log]# cat ipaserver-install.log
........ thousands of lines of logs .....................
2022-10-04T04:15:09Z DEBUG stdout=
2022-10-04T04:15:09Z DEBUG stderr=
2022-10-04T04:15:09Z DEBUG ldappasswd done
2022-10-04T04:15:09Z DEBUG Configuring client side components
2022-10-04T04:15:09Z DEBUG Starting external process
2022-10-04T04:15:09Z DEBUG args=['/usr/sbin/ipa-client-install', '--on-master', '--unattended', '--domain', 'example.com', '--server', 'example.com', '--realm', 'EXAMPLE.COM', '--hostname', 'example.com', '--no-ntp', '--no-ssh', '--no-sshd']
2022-10-04T04:15:10Z DEBUG Process finished, return code=1
2022-10-04T04:15:10Z DEBUG   File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 342, in run
    return cfgr.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/__init__.py", line 570, in main
    master_install(self)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 275, in decorated
    func(installer)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 1001, in install
    raise ScriptError("Configuration of client side components failed!")

2022-10-04T04:15:10Z DEBUG The ipa-server-install command failed, exception: ScriptError: Configuration of client side components failed!
2022-10-04T04:15:10Z ERROR Configuration of client side components failed!
2022-10-04T04:15:10Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

It seems that it's looking for services to be available, but no services are running:
```
[root@a log]# systemctl list-units --type=service --all
  UNIT                           LOAD      ACTIVE   SUB     DESCRIPTION                                        
  certmonger.service             loaded    active   running Certificate monitoring and PKI enrollment          
  dbus.service                   loaded    active   running D-Bus System Message Bus                           
  emergency.service              loaded    inactive dead    Emergency Shell                                    
  oddjobd.service                loaded    active   running privileged operations for unprivileged applications
● plymouth-start.service         not-found inactive dead    plymouth-start.service                             
  rescue.service                 loaded    inactive dead    Rescue Shell                                       
● syslog.service                 not-found inactive dead    syslog.service                                     
  systemd-initctl.service        loaded    inactive dead    initctl Compatibility Daemon                       
  systemd-journald.service       loaded    active   running Journal Service                                    
● systemd-remount-fs.service     masked    inactive dead    systemd-remount-fs.service                         
  systemd-sysusers.service       loaded    inactive dead    Create System Users                                
  systemd-tmpfiles-setup.service loaded    active   exited  Create Volatile Files and Directories              
  systemd-update-done.service    loaded    inactive dead    Update is Completed                                

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

13 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
```

When looking at the logs for the ldap server, I saw this:
```
[04/Oct/2022:04:09:07.318259769 +0000] - WARN - slapd_do_all_nss_ssl_init - ERROR: TLS is not enabled, and the machine is in FIPS mode. Some functionality won't work correctly (for example, users with PBKDF2_SHA256 password scheme won't be able to log in). It's highly advisable to enable TLS on this instance.
[04/Oct/2022:04:09:07.429638077 +0000] - ERR - PBKDF2_SHA256 - Unable to retrieve slot from NSS.
[04/Oct/2022:04:09:07.448098885 +0000] - ERR - PBKDF2_SHA256 - Could not generate pbkdf2_sha256_hash!
```

And for the httpd error log:
```
[root@a log]# cat httpd/error_log 
[Tue Oct 04 04:13:49.910195 2022] [suexec:notice] [pid 2725:tid 140261395274048] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Oct 04 04:13:50.032812 2022] [lbmethod_heartbeat:notice] [pid 2725:tid 140261395274048] AH02282: No slotmem from mod_heartmonitor
[Tue Oct 04 04:13:50.051707 2022] [mpm_event:notice] [pid 2725:tid 140261395274048] AH00489: Apache/2.4.37 (centos) OpenSSL/1.1.1k mod_auth_gssapi/1.6.1 mod_wsgi/4.6.4 Python/3.6 configured -- resuming normal operations
[Tue Oct 04 04:13:50.051755 2022] [core:notice] [pid 2725:tid 140261395274048] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Tue Oct 04 04:15:10.618693 2022] [auth_gssapi:error] [pid 2736:tid 140260743960320] [client 10.0.4.110:40186] GSS ERROR gss_acquire_cred[_from]() failed to get server creds: [Unspecified GSS failure.  Minor code may provide more information ( SPNEGO cannot find mechanisms to negotiate)], referer: https://example.com/ipa/xml
[Tue Oct 04 04:15:11.141653 2022] [mpm_event:notice] [pid 2725:tid 140261395274048] AH00492: caught SIGWINCH, shutting down gracefully
```

I do wonder if this has something to do with NSS vs OpenSSL, and if there are additional configurations / build parameters that need to be included in the Dockerfile in order to get FIPS support for `freeipa-container`?

Thanks!

**Comment by adelton** [comment]
My understanding of https://www.freeipa.org/page/V4/FreeIPA-on-FIPS#How_to_Use

> Set up your system to be in FIPS-enabled mode and install FreeIPA as you would normally do.

was that nothing special needs to be done to get FIPS-enabled FreeIPA.

I took a FIPS-enabled RHEL 8.6 and run the stock `docker.io/freeipa/freeipa-server:centos-8-stream` image with
```
# docker=podman tests/run-master-and-replica.sh docker.io/freeipa/freeipa-server:centos-8-stream
```
and it passed, creating both master and replica containers. Checking
```
# podman exec freeipa-master cat /proc/sys/crypto/fips_enabled
1
# podman exec freeipa-master ipa env fips_mode
  fips_mode: True
```
shows that even FreeIPA is aware that it's FIPS-enabled.

Can you test that? Doesn't it give you what you need?

How does your base CentOS 8 stream base image with FIPS differ from `quay.io/centos/centos:stream8`?

That long traceback you showed ends with
```
2022-10-04T04:15:10Z DEBUG The ipa-server-install command failed, exception: ScriptError: Configuration of client side components failed!
2022-10-04T04:15:10Z ERROR Configuration of client side components failed!
```
so you might want to look for clues in `/var/log/ipaclient-install.log`.

That `systemctl list-units --type=service --all` output is expected -- the `not-found` means that some other service listed `plymouth-start.service` or `syslog.service` (or rather, `syslog.socket`) as `After`, even if the service is not installed. It is expected.

**Comment by ccravens** [comment]
Thank you for the fast response!

So I went ahead and switched to the Docker Hub version of the container `freeipa/freeipa-server:centos-8-stream-4.9.10` to go ahead and test without FIPS, and I'm still having the same issue. I checked the `/var/log/ipaclient-install.log` file and see this:

```
2022-10-04T17:51:14Z DEBUG [try 1]: Forwarding 'schema' to json server 'https://example.com/ipa/json'
2022-10-04T17:51:14Z DEBUG New HTTP connection (example.com)
2022-10-04T17:51:14Z DEBUG HTTP connection destroyed (example.com)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/__init__.py", line 120, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 674, in _auth_complete
    message=u"No valid Negotiate header in server response")
ipalib.errors.KerberosError: No valid Negotiate header in server response
2022-10-04T17:51:14Z DEBUG Destroyed connection context.rpcclient_139774117859400
2022-10-04T17:51:14Z DEBUG   File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 344, in run
    return cfgr.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.6/site-packages/ipaclient/install/client.py", line 3961, in main
    install(self)
  File "/usr/lib/python3.6/site-packages/ipaclient/install/client.py", line 2655, in install
    _install(options)
  File "/usr/lib/python3.6/site-packages/ipaclient/install/client.py", line 2972, in _install
    api.finalize()
  File "/usr/lib/python3.6/site-packages/ipalib/plugable.py", line 753, in finalize
    self.__do_if_not_done('load_plugins')
  File "/usr/lib/python3.6/site-packages/ipalib/plugable.py", line 432, in __do_if_not_done
    getattr(self, name)()
  File "/usr/lib/python3.6/site-packages/ipalib/plugable.py", line 632, in load_plugins
    for package in self.packages:
  File "/usr/lib/python3.6/site-packages/ipalib/__init__.py", line 952, in packages
    ipaclient.remote_plugins.get_package(self),
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/__init__.py", line 128, in get_package
    plugins = schema.get_package(server_info, client)
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/schema.py", line 546, in get_package
    schema = Schema(client)
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/schema.py", line 395, in __init__
    fingerprint, ttl = self._fetch(client, ignore_cache=read_failed)
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/schema.py", line 420, in _fetch
    schema = client.forward(u'schema', **kwargs)['result']
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1146, in forward
    return self._call_command(command, params)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1122, in _call_command
    return command(*params)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1276, in _call
    return self.__request(name, args)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1243, in __request
    verbose=self.__verbose >= 3,
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 674, in _auth_complete
    message=u"No valid Negotiate header in server response")

2022-10-04T17:51:14Z DEBUG The ipa-client-install command failed, exception: KerberosError: No valid Negotiate header in server response
2022-10-04T17:51:14Z ERROR No valid Negotiate header in server response
2022-10-04T17:51:14Z ERROR The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
```

I'm looking into this issue that was previously filed: https://github.com/freeipa/freeipa-container/issues/274

I don't yet have a smoking gun for the issue. I am running this on Kubernetes RKE2 1.22.6, with all security capabilities and `/sys/fs/cgroup` mounted readonly. I have had this working within the past month so I'm not sure what has changed. I have also set SELinux and fapolicyd to Permissive now. I am going to keep investigating this.

**Comment by ccravens** [comment]
Also the differences between our CentOS 8 Stream base image and the Quay is that we run several hardening scripts against the image as well as having S6 installed.

**Comment by ccravens** [comment]
Also here are my `IPA_SERVER_INSTALL_OPTS`:

```json
      {
        name: 'IPA_SERVER_INSTALL_OPTS',
        value: `--unattended --realm=CLUSTER.LOCAL --admin-password='${adminPassword}' --ds-password='${dsPassword}' --master-password='${krbPassword}' --no-ntp --no_hbac_allow --no-ssh --no-sshd --debug`,
      },
```

**Comment by adelton** [comment]
So the issue is not about FIPS at all.

The `AttributeError: 'API' object has no attribute '_remote_plugins'` and `No valid Negotiate header in server response` we've seen reported multiple times but with no definitive reason. The problem is, I was not able to reproduce the issue on any Fedora, CentOS, RHEL, or GitHub Ubuntus 20.04 or 22.04 where we've been testing the container either with docker or with podman.

In https://github.com/freeipa/freeipa-container/issues/274 it turned out to be the `--ip-address` option which you do not use, in https://github.com/freeipa/freeipa-container/issues/383 it was caused by `--privileged` which I assume you do not use.

In https://github.com/freeipa/freeipa-container/issues/383#issuecomment-886708474 the `PrivateTmp` on `httpd.service` was listed as the potential cause. So you might want to try the workaround from there.

**Comment by ccravens** [comment]
@adelton ok I'll go ahead and close this issue and opened a new one to track the fix to document the issue,  the resolution and hopefully help others in the future.

https://github.com/freeipa/freeipa-container/issues/485

Thank you!
