### ISSUE TITLE
'API' object has no attribute '_remote_plugins' Error

### ISSUE THREAD

**Issue by ccravens** [freeipa/freeipa-container#485]
EDIT / RESOLUTION: After a lot of configuration changes and deployment tests, it boiled down to this configuration in the manifest:

```yaml
securityContext:
  capabilities:
    add:
    - ALL
```

I am not sure why the deployment does not work with that configuration or why it causes this behavior / specific error. But by replacing this:

```yaml
securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
    - ALL
```

with this:

```yaml
securityContext:
  readOnlyRootFilesystem: true
```

And the deployment seems to work just fine now! I hope this helps others!

===================================================================================

I'm trying to get FreeIPA container running on my Kubernetes cluster. I have had this working in the past for the last couple of years, but recently I have been getting this error and am unable to identify the culprit so far. My hope is that this issue can document the process of resolution and maybe help others in the future that may find this issue useful.

**My environment:**
Kubernetes Version: `RKE2 v1.22.6+rke2r1`
FreeIPA Version: `freeipa/freeipa-server:centos-8-stream-4.9.10`

**Deployment Manifest:**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ipa
  name: ipa
  namespace: env-9yyr60
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipa
  template:
    metadata:
      labels:
        app: ipa
    spec:
      containers:
        image: freeipa/freeipa-server:centos-8-stream-4.9.10
      - env:
        - name: IPA_SERVER_HOSTNAME
          value: a.ipa.env-9yyr60.svc.cluster.local
        - name: PASSWORD
          value: DVLX7StovcLvNrjwBP62FlLy50zJ3jMy
        - name: IPA_SERVER_INSTALL_OPTS
          value: --unattended --realm=IPA.ENV-9YYR60.SVC.CLUSTER.LOCAL --admin-password='DVLX7StovcLvNrjwBP62FlLy50zJ3jMy'
            --ds-password='tFcVa5oYZmAlp4bKFdvjHoIWIrheIDlP' --master-password='DPoFAv5kbOtxq1vDOuMXfCXDuvTb1bNI'
            --no-ntp --no_hbac_allow --no-ssh --no-sshd --debug
        imagePullPolicy: Always
        name: ipa
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 389
          name: ldap
          protocol: TCP
        - containerPort: 636
          name: ldaps
          protocol: TCP
        - containerPort: 88
          name: krbtcp
          protocol: TCP
        - containerPort: 464
          name: krbpwdtcp
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - ALL
        volumeMounts:
        - mountPath: /data
          name: ipa-a
        - mountPath: /sys/fs/cgroup
          name: cgroups
          readOnly: true
      dnsPolicy: ClusterFirst
      hostname: a
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: env-9yyr60
      serviceAccountName: env-9yyr60
      setHostnameAsFQDN: true
      subdomain: ipa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ipa-a
        persistentVolumeClaim:
          claimName: ipa-a
      - hostPath:
          path: /sys/fs/cgroup
          type: ""
        name: cgroups
```

**Issue:**
The container startup process seems to go well for probably 80-90% of the initial install process. Many entries being added to LDAP, services being started / restarted. But then I'm seeing this error in the logs:
```
Configuring client side components
Starting external process
args=['/usr/sbin/ipa-client-install', '--on-master', '--unattended', '--domain', 'ipa.env-9yyr60.svc.cluster.local', '--server', 'a.ipa.env-9yyr60.svc.cluster.local', '--realm', 'IPA.ENV-9YYR60.SVC.CLUSTER.LOCAL', '--hostname', 'a.ipa.env-9yyr60.svc.cluster.local', '--no-ntp', '--no-ssh', '--no-sshd']
Using existing certificate '/etc/ipa/ca.crt'.
Client hostname: a.ipa.env-9yyr60.svc.cluster.local
Realm: IPA.ENV-9YYR60.SVC.CLUSTER.LOCAL
DNS Domain: ipa.env-9yyr60.svc.cluster.local
IPA Server: a.ipa.env-9yyr60.svc.cluster.local
BaseDN: dc=ipa,dc=env-9yyr60,dc=svc,dc=cluster,dc=local
Configured /etc/sssd/sssd.conf
No valid Negotiate header in server response
The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
Process finished, return code=1
  File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 344, in run
    return cfgr.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/__init__.py", line 566, in main
    master_install(self)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 278, in decorated
    func(installer)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 1006, in install
    raise ScriptError("Configuration of client side components failed!")
```

I then exec into the container and see this in `/var/log/ipaclient-install.log`:
```
2022-10-05T14:12:42Z DEBUG args=['/usr/bin/certutil', '-d', 'sql:/tmp/tmphwq14elb', '-A', '-n', 'CA certificate 1', '-t', 'C,,', '-a', '-f', '/tmp/tmphwq14elb/pwdfile.txt']
2022-10-05T14:12:43Z DEBUG Process finished, return code=0
2022-10-05T14:12:43Z DEBUG stdout=
2022-10-05T14:12:43Z DEBUG stderr=
2022-10-05T14:12:43Z DEBUG failed to find session_cookie in persistent storage for principal 'host/a.ipa.env-9yyr60.svc.cluster.local@IPA.ENV-9YYR60.SVC.CLUSTER.LOCAL'
2022-10-05T14:12:43Z DEBUG trying https://a.ipa.env-9yyr60.svc.cluster.local/ipa/json
2022-10-05T14:12:43Z DEBUG Created connection context.rpcclient_140515139343136
2022-10-05T14:12:43Z DEBUG [try 1]: Forwarding 'schema' to json server 'https://a.ipa.env-9yyr60.svc.cluster.local/ipa/json'
2022-10-05T14:12:43Z DEBUG New HTTP connection (a.ipa.env-9yyr60.svc.cluster.local)
2022-10-05T14:12:43Z DEBUG HTTP connection destroyed (a.ipa.env-9yyr60.svc.cluster.local)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/__init__.py", line 120, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 674, in _auth_complete
    message=u"No valid Negotiate header in server response")
ipalib.errors.KerberosError: No valid Negotiate header in server response
2022-10-05T14:12:43Z DEBUG Destroyed connection context.rpcclient_140515139343136
2022-10-05T14:12:43Z DEBUG   File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 344, in run
    return cfgr.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.6/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.6/site-packages/ipaclient/install/client.py", line 3961, in main
    install(self)
  File "/usr/lib/python3.6/site-packages/ipaclient/install/client.py", line 2655, in install
    _install(options)
  File "/usr/lib/python3.6/site-packages/ipaclient/install/client.py", line 2972, in _install
    api.finalize()
  File "/usr/lib/python3.6/site-packages/ipalib/plugable.py", line 753, in finalize
    self.__do_if_not_done('load_plugins')
  File "/usr/lib/python3.6/site-packages/ipalib/plugable.py", line 432, in __do_if_not_done
    getattr(self, name)()
  File "/usr/lib/python3.6/site-packages/ipalib/plugable.py", line 632, in load_plugins
    for package in self.packages:
  File "/usr/lib/python3.6/site-packages/ipalib/__init__.py", line 952, in packages
    ipaclient.remote_plugins.get_package(self),
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/__init__.py", line 128, in get_package
    plugins = schema.get_package(server_info, client)
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/schema.py", line 546, in get_package
    schema = Schema(client)
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/schema.py", line 395, in __init__
    fingerprint, ttl = self._fetch(client, ignore_cache=read_failed)
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/schema.py", line 420, in _fetch
    schema = client.forward(u'schema', **kwargs)['result']
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1146, in forward
    return self._call_command(command, params)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1122, in _call_command
    return command(*params)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1276, in _call
    return self.__request(name, args)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 1243, in __request
    verbose=self.__verbose >= 3,
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 674, in _auth_complete
    message=u"No valid Negotiate header in server response")

2022-10-05T14:12:43Z DEBUG The ipa-client-install command failed, exception: KerberosError: No valid Negotiate header in server response
2022-10-05T14:12:43Z ERROR No valid Negotiate header in server response
2022-10-05T14:12:43Z ERROR The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
```

I've seen some issues filed that this could be related to the gssapi proxy being down, when the container starts I can confirm the proxy is not started:
```
[root@a /]# systemctl status gssproxy
● gssproxy.service - GSSAPI Proxy Daemon
   Loaded: loaded (/usr/lib/systemd/system/gssproxy.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Oct 05 14:11:20 a.ipa.env-9yyr60.svc.cluster.local systemd[1]: Starting GSSAPI Proxy Daemon...
Oct 05 14:11:20 a.ipa.env-9yyr60.svc.cluster.local systemd[1]: Started GSSAPI Proxy Daemon.
Oct 05 14:12:43 a.ipa.env-9yyr60.svc.cluster.local systemd[1]: Stopping GSSAPI Proxy Daemon...
Oct 05 14:12:43 a.ipa.env-9yyr60.svc.cluster.local systemd[1]: gssproxy.service: Succeeded.
Oct 05 14:12:43 a.ipa.env-9yyr60.svc.cluster.local systemd[1]: Stopped GSSAPI Proxy Daemon.
```

So I tried manually starting the proxy service at the very being of the container being launched via `systemctl status gssproxy`. The proxy successfully starts, but then I get the same error and the proxy is once again dead. At this point I'm not sure what is causing this I have no idea why the services seem to work for the 1st half of the initial install, but then it seems like they aren't starting back up? Thank you!

**Comment by adelton** [comment]
What OS and version is this? How was the RKE2 installed and configured, with what container runtime?

If you test-install K3s on the same OS, will things behave differently? Note that we test on K3s on Ubuntu 20.04 and 22.04 in GitHub Actions: https://github.com/freeipa/freeipa-container/blob/master/.github/workflows/build-test.yaml.

**Comment by ccravens** [comment]
Here is the host-level info:
```
[root@ip-192-168-0-10 ~]# cat /etc/redhat-release 
CentOS Stream release 8

[root@ip-192-168-0-10 ~]# uname -a
Linux 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[root@ip-192-168-0-10 ~]# getenforce 
Enforcing

[root@ip-192-168-0-10 ~]# cat /etc/fapolicyd/fapolicyd.conf | grep permissive
permissive = 0
```

RKE2 was installed just based on the install instructions, they have pretty much automated standing up an RKE2 cluster via rpm install: https://docs.rke2.io/install/quickstart/#1-run-the-installer

There are no SELinux nor fapolicyd rules that have triggered a denial on the nodes that are running the FreeIPA pod.

**Comment by ccravens** [comment]
While poking around at this some additional behavior I felt worth noting, the various services seem to be starting and stopping during the initial install process just fine, however when the error occurs they are all stopped / dead state.

```
[root@a log]# cat ipaserver-install.log | grep systemctl
2022-10-05T14:06:50Z DEBUG b'CMD: systemctl enable dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL ; STDOUT:  ; STDERR: Created symlink /etc/systemd/system/multi-user.target.wants/dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service \xe2\x86\x92 /usr/lib/systemd/system/dirsrv@.service.\n'
2022-10-05T14:07:04Z DEBUG args=['/bin/systemctl', '--system', 'daemon-reload']
2022-10-05T14:07:04Z DEBUG args=['/bin/systemctl', '--system', 'daemon-reload']
2022-10-05T14:07:05Z DEBUG args=['/bin/systemctl', 'restart', 'dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service']
..... Lots of systemctl start / restart / stop / is-active
2022-10-05T14:11:41Z DEBUG args=['/bin/systemctl', 'restart', 'krb5kdc.service']
2022-10-05T14:11:42Z DEBUG args=['/bin/systemctl', 'is-active', 'krb5kdc.service']
2022-10-05T14:11:42Z DEBUG args=['/bin/systemctl', 'is-active', 'dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service']
2022-10-05T14:11:42Z DEBUG args=['/bin/systemctl', 'stop', 'dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service']
2022-10-05T14:11:44Z DEBUG args=['/bin/systemctl', 'start', 'dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service']
2022-10-05T14:12:24Z DEBUG args=['/bin/systemctl', 'stop', 'dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service']
2022-10-05T14:12:27Z DEBUG args=['/bin/systemctl', 'start', 'dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service']
2022-10-05T14:12:30Z DEBUG args=['/bin/systemctl', 'restart', 'krb5kdc.service']
2022-10-05T14:12:31Z DEBUG args=['/bin/systemctl', 'is-active', 'krb5kdc.service']
2022-10-05T14:12:31Z DEBUG args=['/bin/systemctl', 'restart', 'dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service
```

It has also created all of the unit files for systemctl:
```
[root@a log]# ls /data/etc/systemd/system
console-getty.service       dev-hugepages.mount                                getty.target        httpd.service.d                   pki-tomcatd.target.wants          sockets.target.wants           systemd-logind.service
container-ipa.target.wants  dirsrv.target.wants                                getty.target.wants  multi-user.target.wants           pki-tomcatd@pki-tomcat.service.d  sys-fs-fuse-connections.mount  systemd-remount-fs.service
default.target              dirsrv@IPA-ENV-9YYR60-SVC-CLUSTER-LOCAL.service.d  httpd.d             pki-tomcatd-nuxwdog.target.wants  remote-fs.target.wants            sysinit.target.wants           timers.target.wants
```

**Comment by adelton** [comment]
How is the persistent volume created / defined?

**Comment by ccravens** [comment]
This is the PersistentVolumeClaim definition:

```yaml
$ k get pvc ipa-a -n env-c23bjs -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  creationTimestamp: "2022-10-06T03:56:48Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: ipa-a
  namespace: env-c23bjs
  resourceVersion: "43215"
  uid: 3a0c3d6e-346d-404e-8096-a5f8f47ada03
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-3a0c3d6e-346d-404e-8096-a5f8f47ada03
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```

**Comment by ccravens** [comment]
So I've been banging at this pretty much all day without much progress. I have a working deployment from a slightly older environment that I'm comparing running services between the two. In the working environment the running services are:

```bash
[root@a log]# systemctl list-units --type=service --state=running
  UNIT                           LOAD   ACTIVE SUB     DESCRIPTION
  certmonger.service             loaded active running Certificate monitoring and PKI enrollment
  dbus-broker.service            loaded active running D-Bus System Message Bus
  gssproxy.service               loaded active running GSSAPI Proxy Daemon
  httpd.service                  loaded active running The Apache HTTP Server
  ipa-custodia.service           loaded active running IPA Custodia Service
  kadmin.service                 loaded active running Kerberos 5 Password-changing and Administration
  krb5kdc.service                loaded active running Kerberos 5 KDC
  oddjobd.service                loaded active running privileged operations for unprivileged applications
  pki-tomcatd@pki-tomcat.service loaded active running PKI Tomcat Server pki-tomcat
  sssd.service                   loaded active running System Security Services Daemon
  systemd-journald.service       loaded active running Journal Service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
11 loaded units listed.
```

However, in the environment that's giving me this error the only services that are running after the error are:

```bash
[root@a /]# systemctl list-units --type=service --state=running
  UNIT                     LOAD   ACTIVE SUB     DESCRIPTION                                        
  certmonger.service       loaded active running Certificate monitoring and PKI enrollment
  dbus-broker.service      loaded active running D-Bus System Message Bus
  oddjobd.service          loaded active running privileged operations for unprivileged applications
  systemd-journald.service loaded active running Journal Service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
4 loaded units listed.
```

But I am able to manually start each service and they all start up just fine right after the error:

```bash
[root@a log]# systemctl list-units --type=service --state=running
  UNIT                                            LOAD   ACTIVE SUB     DESCRIPTION                                           
  certmonger.service                              loaded active running Certificate monitoring and PKI enrollment
  dbus-broker.service                             loaded active running D-Bus System Message Bus
  dirsrv@IPA-ENV-RKCCM1-SVC-CLUSTER-LOCAL.service loaded active running 389 Directory Server IPA-ENV-RKCCM1-SVC-CLUSTER-LOCAL.
  gssproxy.service                                loaded active running GSSAPI Proxy Daemon
  httpd.service                                   loaded active running The Apache HTTP Server
  ipa-custodia.service                            loaded active running IPA Custodia Service
  kadmin.service                                  loaded active running Kerberos 5 Password-changing and Administration
  krb5kdc.service                                 loaded active running Kerberos 5 KDC
  oddjobd.service                                 loaded active running privileged operations for unprivileged applications
  pki-tomcatd@pki-tomcat.service                  loaded active running PKI Tomcat Server pki-tomcat
  sssd.service                                    loaded active running System Security Services Daemon
  systemd-journald.service                        loaded active running Journal Service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
12 loaded units listed.
```

**Comment by ccravens** [comment]
This is the python code where the exception is being thrown at `/usr/lib/python3.9/site-packages/ipalib/rpc.py`.

The `www-authenticate` does not have `negotiate` in the header.

```python
    def _auth_complete(self, response):
        if self._sec_context:
            header = response.getheader('www-authenticate', '')
            token = None
            for field in header.split(','):
                k, _dummy, v = field.strip().partition(' ')
                if k.lower() == 'negotiate':
                    try:
                        token = base64.b64decode(v.encode('ascii'))
                        break
                    # b64decode raises TypeError on invalid input
                    except (TypeError, UnicodeError):
                        pass
            if not token:
                raise errors.KerberosError(
                    message=u"No valid Negotiate header in server response")
            token = self._sec_context.step(token=token)
            if self._sec_context.complete:
                self._sec_context = None
                return True
            self._set_auth_header(token)
            return False
        elif response.status == 401:
            self.get_auth_info(use_cookie=False)
            return False
        return True
```

**Comment by ccravens** [comment]
Another interesting behavior I've noticed is that this error is causing the pod to crash (notice restart). I confirmed this by exec'ing into the container and my terminal connection was killed when the error happened.

```
[k8s]$ k get pods -n env-n0qg5w
NAME                                 READY   STATUS    RESTARTS      AGE
ipa-7bb7b8894b-lrfkh                 3/3     Running   1 (30s ago)   6m55s
```

**Comment by ccravens** [comment]
@adelton I was able to boil down the issue to this:

```yaml
securityContext:
  capabilities:
    add:
    - ALL
```

By having that in the manifest, it caused that error. I honestly do not know why. But my deployment seems solid now. I appreciate your feedback and support in resolving this matter and I hope my  feedback can help others as well. Closing the issue
