### ISSUE TITLE
failed to find session_cookie in persistent storage for principal

### ISSUE THREAD

**Issue by Youpiiiii** [freeipa/freeipa-container#500]
I'm stuck on install.

`docker run --privileged --name freeipa -ti -h freeipa.example.local -v /var/lib/ipa-data:/data:Z --sysctl net.ipv6.conf.all.disable_ipv6=0 freeipa/freeipa-server:almalinux-9 --unattended --realm=EXAMPLE.LOCAL --admin-password=password --ds-password=password`

`2022-11-29T03:11:00Z DEBUG failed to find session_cookie in persistent storage for principal 'host/freeipa.example.local@EXAMPLE.LOCAL'
2022-11-29T03:11:12Z DEBUG trying https://freeipa.example.local/ipa/json
2022-11-29T03:11:12Z DEBUG Created connection context.rpcclient_139976984968640
2022-11-29T03:11:12Z DEBUG [try 1]: Forwarding 'schema' to json server 'https://freeipa.example.local/ipa/json'
2022-11-29T03:11:12Z DEBUG New HTTP connection (freeipa.example.local)
2022-11-29T03:11:12Z DEBUG HTTP connection destroyed (freeipa.example.local)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipaclient/remote_plugins/__init__.py", line 120, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 673, in _auth_complete
    raise errors.KerberosError(
ipalib.errors.KerberosError: No valid Negotiate header in server response`

Do you have an idea ?

**Comment by adelton** [comment]
Based on previous issues, I'm fairly sure the problem is with that `--privileged` option.

In which documentation did you see that option recommended / needed for the FreeIPA container?

**Comment by Youpiiiii** [comment]
As much for me, I had permission problems when I wasn't using it. I thought it was helping me.
My mistake wasn't to use the same user to start docker run and the value "userns-remap".
A big thank you @adelton for your quick feedback.

**Comment by Youpiiiii** [comment]
I have a question @adelton. What misled me was to use docker compose. I can't find a working configuration.
Is it possible to use freeipa with docker compose ? If yes, have you an example ?

**Comment by adelton** [comment]
In general you will just want to rewrite the `docker run` parameters into the `docker-compose.yml` syntax.

You can use https://github.com/adelton/webauthinfra/blob/master/docker-compose.yml as an inspiration (even if that one is for a multi-container application setup with FreeIPA server, not just FreeIPA).
