### ISSUE TITLE
fresh freeipa fail to configure CA during docker initial startup (rocky-9 and almalinux-8)

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [freeipa/freeipa-container#503]
installation passing until : 

```
2022-12-12T11:55:10Z DEBUG Starting external process
2022-12-12T11:55:10Z DEBUG args=['/usr/sbin/pkispawn', '-s', 'CA', '-f', '/tmp/tmpz85inkov', '--debug', '--log-file', '/var/log/pki/pki-ca-spawn.20221212125510.log']
2022-12-12T11:55:10Z DEBUG Process finished, return code=1
2022-12-12T11:55:10Z DEBUG stdout=Loading deployment configuration from /tmp/tmpz85inkov.
Installation log: /var/log/pki/pki-ca-spawn.20221212125510.log

2022-12-12T11:55:10Z DEBUG stderr=Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/pki/server/pkispawn.py", line 1023, in <module>
    main(sys.argv)
  File "/usr/lib/python3.9/site-packages/pki/server/pkispawn.py", line 559, in main
    pkilogging.enable_pki_logger(args.log_file)
  File "/usr/lib/python3.9/site-packages/pki/server/deployment/pkilogging.py", line 66, in enable_pki_logger
    pathlib.Path(filename).touch()
  File "/usr/lib64/python3.9/pathlib.py", line 1315, in touch
    fd = self._raw_open(flags, mode)
  File "/usr/lib64/python3.9/pathlib.py", line 1127, in _raw_open
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/pki/pki-ca-spawn.20221212125510.log'

2022-12-12T11:55:10Z CRITICAL Failed to configure CA instance
2022-12-12T11:55:10Z CRITICAL See the installation logs and the following files/directories for more information:
2022-12-12T11:55:10Z CRITICAL   /var/log/pki/pki-tomcat
2022-12-12T11:55:10Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 686, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 672, in run_step
    method()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/cainstance.py", line 646, in __spawn_instance
    DogtagInstance.spawn_instance(
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dogtaginstance.py", line 227, in spawn_instance
    self.handle_setup_error(e)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dogtaginstance.py", line 604, in handle_setup_error
    raise RuntimeError(
RuntimeError: CA configuration failed.

2022-12-12T11:55:10Z DEBUG   [error] RuntimeError: CA configuration failed.
2022-12-12T11:55:10Z DEBUG Keep pkispawn files for step 2
2022-12-12T11:55:10Z DEBUG   File "/usr/lib/python3.9/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/cli.py", line 344, in run
    return cfgr.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/__init__.py", line 566, in main
    master_install(self)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/install.py", line 278, in decorated
    func(installer)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/install.py", line 909, in install
    ca.install_step_0(False, None, options, custodia=custodia)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/ca.py", line 404, in install_step_0
    ca.configure_instance(
  File "/usr/lib/python3.9/site-packages/ipaserver/install/cainstance.py", line 506, in configure_instance
    self.start_creation(runtime=runtime)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 686, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 672, in run_step
    method()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/cainstance.py", line 646, in __spawn_instance
    DogtagInstance.spawn_instance(
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dogtaginstance.py", line 227, in spawn_instance
    self.handle_setup_error(e)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dogtaginstance.py", line 604, in handle_setup_error
    raise RuntimeError(

2022-12-12T11:55:10Z DEBUG The ipa-server-install command failed, exception: RuntimeError: CA configuration failed.
2022-12-12T11:55:10Z ERROR CA configuration failed.
2022-12-12T11:55:10Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
tail: ipaserver-install.log: file truncated
2022-12-12T11:55:13Z DEBUG Logging to /var/log/ipaserver-install.log
```

After it it breaks and install script restart with endless loop 

```
2022-12-12T11:55:14Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 686, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 672, in run_step
    method()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dsinstance.py", line 555, in __create_instance
    sds.create_from_args(general, slapd, backends, None)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 685, in create_from_args
    self._prepare_ds(general, slapd, backends)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 612, in _prepare_ds
    assert_c(len(insts) == 0, "Another instance named '%s' may already exist" % slapd['instance_name'])
  File "/usr/lib/python3.9/site-packages/lib389/utils.py", line 1274, in assert_c
    raise AssertionError(msg)
AssertionError: Another instance named 'BLAUW1-HELLO-ME' may already exist

2022-12-12T11:55:14Z DEBUG   [error] AssertionError: Another instance named 'BLAUW1-HELLO-ME' may already exist
2022-12-12T11:55:14Z DEBUG   File "/usr/lib/python3.9/site-packages/ipapython/admintool.py", line 180, in execute
```

**Comment by jpVm5jYYRE1VIKL** [comment]
this is my docker compose : 

```
services:
  freeipa:
    container_name: freeipa
    image: freeipa/freeipa-server:almalinux-9
    tty: true
    stdin_open: true
    env_file:
      - env
    networks:
      - freeipa
    ports:
      - '80:80'
      - '443:443'
      - '389:389'
      - '636:636'

    command:
      - --domain=blauw1.hello.me
      - --realm=blauw1.hello.me
      - --http-pin=pass1
      - --dirsrv-pin=pass2
      - --ds-password=pass3
      - --admin-password=pass4
      - --no-host-dns
      - --no-ntp
      - --unattended

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
#    security_opt:
#      - "seccomp:unconfined"
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/cache
      - /tmp
    volumes:
      - ./conf/data:/data  
      - ./conf/logs:/var/logs
      - ./conf/log:/var/log
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  freeipa
```

OS : 

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by jpVm5jYYRE1VIKL** [comment]
@adelton i tried to delete whole directory ./conf. It is automatically created . As i told i did complete fresh startup. 
In moment of startup ./conf not exist.

**Comment by jpVm5jYYRE1VIKL** [comment]
Solved with removal another volumes . Thanks 

```
    volumes:
      - ./conf/data:/data  
```
