### ISSUE TITLE
pki-tomcatd Service: STOPPED - unable to start it

### ISSUE THREAD

**Issue by x3nb63** [freeipa/freeipa-container#519]
My setup has 3 replicas and one  died, so its down to two. (I am actually about to replace the dead one - but fail, because ...)

The two living replicas run image `quay.io/freeipa/freeipa-server@sha256:aa9da09b71ea8e01a46de435b93346f3e6a751d3c9aadcd723fcfaedda20ff01` since October 31st 2022. This was some build of the `centos-8-stream` tag then and they were starting up and running fine.

WebUI still works and does most things, however, PKI operations fail and inspection both instance I see:

```
# ipactl status
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
named Service: RUNNING
httpd Service: RUNNING
ipa-custodia Service: RUNNING
pki-tomcatd Service: STOPPED
ipa-otpd Service: RUNNING
ipa-dnskeysyncd Service: RUNNING
1 service(s) are not running
```

I have no idea when or why pki-tomcatd stopped. Starting it now fails.

As far as I digged the actual problem is revealed deep down by `/data/var/log/pki/pki-tomcat/acme/debug.2023-02-15.log`:
```
2023-02-15 13:34:23 [main] INFO: Starting ACME engine
2023-02-15 13:34:23 [main] INFO: ACME configuration directory: /data/var/lib/pki/pki-tomcat/conf/acme
2023-02-15 13:34:23 [main] INFO: Loading ACME engine config from /data/var/lib/pki/pki-tomcat/conf/acme/engine.conf
2023-02-15 13:34:23 [main] INFO: - enabled: false
2023-02-15 13:34:23 [main] INFO: - base URL: https://idm1.domain.tld/acme
2023-02-15 13:34:23 [main] INFO: - nonces persistent: null
2023-02-15 13:34:23 [main] INFO: - wildcard: false
2023-02-15 13:34:23 [main] INFO: - nonce retention: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO: - authorization retention:
2023-02-15 13:34:23 [main] INFO:   - pending: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO:   - invalid: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO:   - valid: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO: - order retention:
2023-02-15 13:34:23 [main] INFO:   - pending: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO:   - invalid: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO:   - ready: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO:   - processing: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO:   - valid: {"length":30,"unit":"MINUTES"}
2023-02-15 13:34:23 [main] INFO: - certificate retention: {"length":30,"unit":"DAYS"}
2023-02-15 13:34:23 [main] INFO: Loading ACME metadata from /usr/share/pki/acme/conf/metadata.conf
2023-02-15 13:34:23 [main] INFO: Loading ACME database config from /data/var/lib/pki/pki-tomcat/conf/acme/database.conf
2023-02-15 13:34:23 [main] INFO: Initializing ACME database
2023-02-15 13:34:23 [main] INFO: Loading LDAP database configuration from /etc/pki/pki-tomcat/ca/CS.cfg
2023-02-15 13:34:23 [main] WARNING: The basedn parameter has been deprecated. Use baseDN instead.
2023-02-15 13:34:23 [main] INFO: - base DN: ou=acme,o=ipaca
2023-02-15 13:34:24 [main] SEVERE: LdapBoundConnFactory: Unable to connect to LDAP server: Authentication failed
netscape.ldap.LDAPException: Authentication failed (48)
        at netscape.ldap.LDAPSaslBind.checkForSASLBindCompletion(Unknown Source)
        at netscape.ldap.LDAPSaslBind.bind(Unknown Source)
        at netscape.ldap.LDAPSaslBind.bind(Unknown Source)
        at netscape.ldap.LDAPConnection.authenticate(Unknown Source)
        at netscape.ldap.LDAPConnection.authenticate(Unknown Source)
        at netscape.ldap.LDAPConnection.checkClientAuth(Unknown Source)
        at netscape.ldap.LDAPConnection.connect(Unknown Source)
...
```

this, i suspect, is  because its using credentials from `/data/var/lib/pki/pki-tomcat/conf/acme/realm.conf`.  This file I see for the very first time ever, which also goes for its content: there is a user I've not seen exists anywhere and a password which looks like auto-generated - perhaps when enrolling this replica?

The LDAP server itself works, ie. having a root shell and getting a `kinit admin` ticket I can use ldapsearch just fine, WebUI also allows logins, lists users, hosts, ... as usual.

How to get this tomcat running again?

**Comment by x3nb63** [comment]
all right, [this blog article](https://floblanc.wordpress.com/2017/09/11/troubleshooting-freeipa-pki-tomcatd-fails-to-start/) made me discover the cert tomcat uses to authenticate with LDAP was expired .... that I could fix with `ipa-cert-fix` tool on one machine.

then on the second machine the @getcert list@ + @getcert resubmit -i ...@ did get the renewal process to `CA_WORKING` state but it does not appear to ever complete - here I got stuck again.

**Comment by adelton** [comment]
Since the issue(s) you are hitting seem to be deep in the generic FreeIPA territory and not related to the fact that the replicas are running containerized, I'd suggest to ask the question at freeipa-users@lists.fedorahosted.org / https://lists.fedoraproject.org/admin/lists/freeipa-users.lists.fedorahosted.org/.

**Comment by x3nb63** [comment]
will do if I stay stuck here

what you think is the cause I ran into this?  I don't see tickets with this sort of problem.

Is it cause I neglected upgrading the container image builds for too long? (roughly 6+ months)

**Comment by x3nb63** [comment]
i failed to repair the second instance

however, after some struggle with Kubernetes probes I succeeded in re-creating the dead third instance from the first instance and then could re-create the second instance too.

after that I finally upgraded the first instance to the current `centos-8-stream` container image and this time all migrations succeeded on their own

I suspect the expired certs is what killed the third instance initially ...
