### ISSUE TITLE
Failed to create /system.slice/containerd.service/init.scope

### ISSUE THREAD

**Issue by SongKeTong** [freeipa/freeipa-container#522]
It works ok with a centos host, but return error when with a ubuntu host. (5.4.0-84-generic #94~18.04.1-Ubuntu)

docker run -ti -h ipa.test.com --read-only -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /var/lib/ipa-data:/data:Z --sysctl net.ipv6.conf.all.disable_ipv6=0 -p 192.168.1.192:443:443 -p 192.168.1.192:389:389 -p 192.168.1.192:53:53 -p 192.168.1.192:53:53/udp -p 192.168.1.192:80:80 -p 192.168.1.192:636:636 -p 192.168.1.192:88:88 -p 192.168.1.192:464:464 -p 192.168.1.192:88:88/udp -p 192.168.1.192:464:464/udp -p 192.168.1.192:123:123/udp test/ipa

systemd 250-12.el9_1.3 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.
Failed to create /system.slice/containerd.service/init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

**Comment by SongKeTong** [comment]
I add --privileged in my command, but it failed when install ipa-client ,but I don't want to install the client

2023-04-04T03:17:38Z DEBUG The ipa-server-install command failed, exception: ScriptError: Configuration of client side components failed!
2023-04-04T03:17:38Z ERROR Configuration of client side components failed!
2023-04-04T03:17:38Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

**Comment by adelton** [comment]
The tests we run in GitHub Actions use Ubuntu 22.04 or 20.04. The 18.04 is too old to have any reasonable advice at this point.

You should never need to use `--privileged`.

Installation / configuration of the client is part of the installation of the FreeIPA master. If this is your first time installing FreeIPA, I'd suggest you do that on a VM, not in container, to familiarize yourself with the concept without the added complexity of the containerized setup.

**Comment by SongKeTong** [comment]
we have to use ipa-server on Ubuntu1804，Could you help me check what the error is.


2023-04-06T06:50:33Z DEBUG Starting external process
2023-04-06T06:50:33Z DEBUG args=['/usr/bin/certutil', '-d', 'sql:/tmp/tmphtt4ph3r', '-A', '-n', 'CA certificate 1', '-t', 'C,,', '-a', '-f', '/tmp/tmphtt4ph3r/pwdfile.txt']
2023-04-06T06:50:33Z DEBUG Process finished, return code=0
2023-04-06T06:50:33Z DEBUG stdout=
2023-04-06T06:50:33Z DEBUG stderr=
2023-04-06T06:50:33Z DEBUG failed to find session_cookie in persistent storage for principal 'host/userserver.cjbdi.com@CJBDI.COM'
2023-04-06T06:50:57Z DEBUG trying https://userserver.cjbdi.com/ipa/json
2023-04-06T06:50:57Z DEBUG Created connection context.rpcclient_140598823160272
2023-04-06T06:50:57Z DEBUG [try 1]: Forwarding 'schema' to json server 'https://userserver.cjbdi.com/ipa/json'
2023-04-06T06:50:57Z DEBUG New HTTP connection (userserver.cjbdi.com)
2023-04-06T06:50:57Z DEBUG HTTP connection destroyed (userserver.cjbdi.com)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipaclient/remote_plugins/__init__.py", line 120, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 724, in single_request
  if not self._auth_complete(response):
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 673, in _auth_complete
    raise errors.KerberosError(
ipalib.errors.KerberosError: No valid Negotiate header in server response
2023-04-06T06:50:57Z DEBUG Destroyed connection context.rpcclient_140598823160272
2023-04-06T06:50:57Z DEBUG   File "/usr/lib/python3.9/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/cli.py", line 344, in run
    return cfgr.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.9/site-packages/ipaclient/install/client.py", line 3976, in main
    install(self)
  File "/usr/lib/python3.9/site-packages/ipaclient/install/client.py", line 2686, in install
    _install(options, dict())
  File "/usr/lib/python3.9/site-packages/ipaclient/install/client.py", line 115, in inner
    func(options, tdict)
  File "/usr/lib/python3.9/site-packages/ipaclient/install/client.py", line 2970, in _install
    api.finalize()
  File "/usr/lib/python3.9/site-packages/ipalib/plugable.py", line 753, in finalize
    self.__do_if_not_done('load_plugins')
  File "/usr/lib/python3.9/site-packages/ipalib/plugable.py", line 432, in __do_if_not_done
    getattr(self, name)()
  File "/usr/lib/python3.9/site-packages/ipalib/plugable.py", line 632, in load_plugins
    for package in self.packages:
  File "/usr/lib/python3.9/site-packages/ipalib/__init__.py", line 955, in packages
    ipaclient.remote_plugins.get_package(self),
  File "/usr/lib/python3.9/site-packages/ipaclient/remote_plugins/__init__.py", line 128, in get_package
  plugins = schema.get_package(server_info, client)
  File "/usr/lib/python3.9/site-packages/ipaclient/remote_plugins/schema.py", line 546, in get_package
    schema = Schema(client)
  File "/usr/lib/python3.9/site-packages/ipaclient/remote_plugins/schema.py", line 395, in __init__
    fingerprint, ttl = self._fetch(client, ignore_cache=read_failed)
  File "/usr/lib/python3.9/site-packages/ipaclient/remote_plugins/schema.py", line 420, in _fetch
    schema = client.forward(u'schema', **kwargs)['result']
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 1146, in forward
    return self._call_command(command, params)
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 1122, in _call_command
    return command(*params)
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 1276, in _call
    return self.__request(name, args)
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 1239, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.9/site-packages/ipalib/rpc.py", line 673, in _auth_complete
    raise errors.KerberosError(

2023-04-06T06:50:57Z DEBUG The ipa-client-install command failed, exception: KerberosError: No valid Negotiate header in server response
2023-04-06T06:50:57Z ERROR No valid Negotiate header in server response
2023-04-06T06:50:57Z ERROR The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information

**Comment by adelton** [comment]
We know this error to be closely related to the use of `--privileged` or equivalent: https://github.com/freeipa/freeipa-container/issues/485.

**Comment by adelton** [comment]
You might want to try to debug with
```
tests/run-partial-tests.sh Dockerfile.centos-9-stream
```
You can also try to add `--tmpfs /run --tmpfs /tmp` to the `docker run` command that you use.

**Comment by SongKeTong** [comment]
I got the same error on ubuntu 20.04,  If I don't use  use --privileged. I got 

Failed to create /docker/e6451d20b54e381e7e51f5a022b49e477a3d82c9226fe81e38ac762cfec9c77b/init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...



After I add  --privileged, I got ipa-client-install error.
If I used the wrong docker image? which image should I choose to run on the ubuntu host,

**Comment by SongKeTong** [comment]
I add --tmpfs /run --tmpfs /tmp ,I got the same error in ipa-client-install;

and I test with "tests/run-partial-tests.sh Dockerfile.centos-9-stream", I got the follow result:

.......
21 files removed
Removing intermediate container 0d6494737454
 ---> ac484ee4ed53
Step 7/14 : RUN test $( getent passwd | grep -E "^(dirsrv:x:389|ipaapi:x:289|kdcproxy:x:288|pkiuser:x:17):" | wc -l ) -eq 4
 ---> Running in 1fc2c73690d4
Removing intermediate container 1fc2c73690d4
 ---> e2474e0c9ae5
Step 8/14 : RUN systemctl mask rpc-gssd.service
 ---> Running in 22f1ebab4dfb
Created symlink /etc/systemd/system/rpc-gssd.service → /dev/null.
Removing intermediate container 22f1ebab4dfb
 ---> b193fbe542fc
Step 9/14 : RUN test -f /etc/machine-id && ! test -s /etc/machine-id
 ---> Running in 38a0a5da2e7f
Removing intermediate container 38a0a5da2e7f
 ---> 710659fa97d1
Step 10/14 : RUN test -z "$container"
 ---> Running in f5b8fc2628b2
Removing intermediate container f5b8fc2628b2
 ---> f2634ee7b83b
Step 11/14 : ENV container oci
 ---> Running in 8286525ef4e1
Removing intermediate container 8286525ef4e1
 ---> 742178bccc87
Step 12/14 : RUN echo "DefaultLimitNOFILE=1024" >> /etc/systemd/system.conf
 ---> Running in 580e54f4cce0
Removing intermediate container 580e54f4cce0
 ---> ae127df13c7b
Step 13/14 : ENTRYPOINT [ "/usr/sbin/init" ]
 ---> Running in ed587fa7fbcd
Removing intermediate container ed587fa7fbcd
 ---> 3589ea6d17b0
Step 14/14 : STOPSIGNAL RTMIN+3
 ---> Running in 4103ef82881a
Removing intermediate container 4103ef82881a
 ---> 8eec56967650
Successfully built 8eec56967650
Successfully tagged localhost/freeipa-server-test:centos-9-stream
Sending build context to Docker daemon  65.54kB
Step 1/2 : FROM localhost/freeipa-server-test:centos-9-stream
 ---> 8eec56967650
Step 2/2 : VOLUME [ "/var/log/journal" ]
 ---> Running in 5425885a3610
Removing intermediate container 5425885a3610
 ---> 902212f16ad3
Successfully built 902212f16ad3
Successfully tagged localhost/freeipa-server-test-addons:centos-9-stream
+ docker run --name freeipa-server-container-centos-9-stream -d -h ipa.example.test --tmpfs /run --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup:ro --sysctl net.ipv6.conf.all.disable_ipv6=0 localhost/freeipa-server-test-addons:centos-9-stream
aa6c45d8c5dc4cc86d7abb93f41c0246f3904ffd7805c2d4386fa860ac00ee9e
Executing ./systemd-container-failed.sh freeipa-server-container-centos-9-stream
● ipa.example.test
    State: running
    Units: 148 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Thu 2023-04-06 08:47:09 UTC; 2s ago
  systemd: 252-8.el9
  Tainted: cgroupsv1
   CGroup: /docker/aa6c45d8c5dc4cc86d7abb93f41c0246f3904ffd7805c2d4386fa860ac00ee9e
           ├─58 systemctl status --no-pager -l
           ├─init.scope
           │ └─1 /usr/sbin/init
           └─system.slice
             ├─crond.service
             │ └─48 /usr/sbin/crond -n
             ├─dbus-broker.service
             │ ├─49 /usr/bin/dbus-broker-launch --scope system --audit
             │ └─50 dbus-broker --log 4 --controller 9 --machine-id 9ebdd6cf174c4e4682a9bdad4f7581fe --max-bytes 536870912 --max-fds 4096 --max-matches 16384 --audit
             ├─gssproxy.service
             │ └─41 /usr/sbin/gssproxy -D
             ├─rpcbind.service
             │ └─35 /usr/bin/rpcbind -w -f
             ├─systemd-journald.service
             │ └─29 /usr/lib/systemd/systemd-journald
             └─systemd-logind.service
               └─40 /usr/lib/systemd/systemd-logind
running
OK ./systemd-container-failed.sh.
Sending build context to Docker daemon  67.07kB
Step 1/14 : FROM localhost/freeipa-server-test:centos-9-stream
 ---> 8eec56967650
Step 2/14 : RUN find /etc/systemd/system /usr/lib/systemd/system/{basic,multi-user,sysinit}.target.wants -type l \! -lname /dev/null | xargs rm -v
 ---> Running in 893d29696293
removed '/etc/systemd/system/multi-user.target.wants/crond.service'
removed '/etc/systemd/system/multi-user.target.wants/remote-fs.target'
removed '/etc/systemd/system/multi-user.target.wants/sssd.service'
removed '/etc/systemd/system/multi-user.target.wants/rpcbind.service'
removed '/etc/systemd/system/multi-user.target.wants/chronyd.service'
removed '/etc/systemd/system/multi-user.target.wants/nfs-client.target'
removed '/etc/systemd/system/timers.target.wants/logrotate.timer'
removed '/etc/systemd/system/timers.target.wants/dnf-makecache.timer'
removed '/etc/systemd/system/sockets.target.wants/rpcbind.socket'
removed '/etc/systemd/system/sockets.target.wants/dbus.socket'
removed '/etc/systemd/system/ctrl-alt-del.target'
removed '/etc/systemd/system/dbus.service'
removed '/etc/systemd/system/getty.target.wants/getty@tty1.service'
removed '/etc/systemd/system/sysinit.target.wants/selinux-autorelabel-mark.service'
removed '/etc/systemd/system/sysinit.target.wants/nis-domainname.service'
removed '/etc/systemd/system/sysinit.target.wants/systemd-network-generator.service'
removed '/etc/systemd/system/remote-fs.target.wants/nfs-client.target'
removed '/usr/lib/systemd/system/multi-user.target.wants/systemd-update-utmp-runlevel.service'
removed '/usr/lib/systemd/system/multi-user.target.wants/systemd-user-sessions.service'
removed '/usr/lib/systemd/system/multi-user.target.wants/systemd-ask-password-wall.path'
removed '/usr/lib/systemd/system/multi-user.target.wants/systemd-logind.service'
removed '/usr/lib/systemd/system/multi-user.target.wants/getty.target'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-journald.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/sys-kernel-tracing.mount'
removed '/usr/lib/systemd/system/sysinit.target.wants/sys-kernel-debug.mount'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-update-done.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-journal-catalog-update.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-machine-id-commit.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-journal-flush.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/dev-mqueue.mount'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-ask-password-console.path'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-sysusers.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/sys-kernel-config.mount'
removed '/usr/lib/systemd/system/sysinit.target.wants/sys-fs-fuse-connections.mount'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-firstboot.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/dev-hugepages.mount'
removed '/usr/lib/systemd/system/sysinit.target.wants/ldconfig.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-update-utmp.service'
removed '/usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service'
Removing intermediate container 893d29696293
 ---> 583e4a8818f9
Step 3/14 : RUN systemctl mask systemd-logind.service && mv /usr/lib/systemd/system/systemd-logind.service /usr/lib/systemd/system/systemd-logind.service-disable-dbus
 ---> Running in fd0db1f8dd8a
Created symlink /etc/systemd/system/systemd-logind.service → /dev/null.
Removing intermediate container fd0db1f8dd8a
 ---> 98cbbfe9972c
Step 4/14 : COPY patches/minimal-fedora-37.patch /root/
COPY failed: file not found in build context or excluded by .dockerignore: stat patches/minimal-fedora-37.patch: file does not exist

**Comment by adelton** [comment]
> I add --tmpfs /run --tmpfs /tmp ,I got the same error in ipa-client-install;

Have you removed that `--privileged` when doing that?

> and I test with "tests/run-partial-tests.sh Dockerfile.centos-9-stream", I got the follow result:
>  [...]
>       Step 4/14 : COPY patches/minimal-fedora-37.patch /root/
>       COPY failed: file not found in build context or excluded by .dockerignore: stat patches/minimal-fedora-37.patch: file does not exist

All I can say is that file is in the master branch of this repository (https://github.com/freeipa/freeipa-container/blob/master/patches/minimal-fedora-37.patch) so something is broken on your side.

**Comment by SongKeTong** [comment]
I remove --privileged and test again, it still failed.

But when I only set -p option with 389 and 443 ,it work well, so I think there maybe some port in used. thanks for your help.

**Comment by adelton** [comment]
Thanks for reporting back.
