### ISSUE TITLE
`read-only` option causes error

### ISSUE THREAD

**Issue by Aetylus** [freeipa/freeipa-container#553]
When attempting to setup the container using the `--read-only` option, e.g.
```sh
$ sudo podman run --name freeipa-server -ti \
 -h ipa.example.test \
 --read-only \
 -v /var/lib/ipa-data:/data:Z \
 freeipa/freeipa-server:rocky-9
 ```
 The installation fails:
 ```
Installation aborted
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
FreeIPA server configuration failed.
```
In the file referred to in the container, I see the following towards the end
```
2023-08-10T22:25:15Z DEBUG LDAP is not connected, can not retrieve NetBIOS name
2023-08-10T22:25:19Z DEBUG   File "/usr/lib/python3.9/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/cli.py", line 344, in run
    return cfgr.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 358, in run
    self.validate()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 368, in validate
    for _nothing in self._validator():
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 455, in _handle_validate_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 633, in _configure
    next(validator)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 455, in _handle_validate_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/__init__.py", line 564, in main
    master_install_check(self)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/install.py", line 278, in decorated
    func(installer)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/install.py", line 765, in install_check
    raise ScriptError("Installation aborted")

2023-08-10T22:25:19Z DEBUG The ipa-server-install command failed, exception: ScriptError: Installation aborted
2023-08-10T22:25:19Z ERROR Installation aborted
2023-08-10T22:25:19Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

However, removing the `read-only` option and running the command as
```
$ sudo podman run --name freeipa-server -ti \
 -h ipa.example.test \
 -v /var/lib/ipa-data:/data:Z \
 freeipa/freeipa-server:rocky-9
```
appears to work and install without issue.

This is on Fedora Server 38 with Podman 4.5.1, and I've confirmed the suggested SELinux boolean has been configured:
```
$ sudo getsebool container_manage_cgroup
container_manage_cgroup --> on
```

Am I doing something wrong? Is there a reason the `read-only` is specifically suggested, and why it doesn't seem to work here?

**Comment by adelton** [comment]
How did you configure the FreeIPA server, either interactively, or using `ipa-server-install-options`?

We recommend the read-only approach because that has a higher chance of guaranteeing that the container will continue working even after restart / after being recreated. If during its operation the server writes to the writeable layer outside of `/data`, those changes will be lost when the container gets created from scratch.

So in a sense it is a good thing that the setup failed for you because it means something in the `ipa-server-install` or the components it configures relied on writing to a location we don't have covered with the `/data` mechanism, and we get a chance of fixing it rather than giving you false sense of a stable container that has parts of what it needs in a location where it can get easily lost.

**Comment by adelton** [comment]
> I'm configuring it interactively through the command line prompts.

Alright, and what selections did you make (so that we can try to reproduce it with the same settings)?

**Comment by Aetylus** [comment]
The options used are:

```
Do you want to configure integrated DNS (BIND)?: no
Server host name: ipa.example.test
Please confirm the domain name: example.test
Please provide a realm name: EXAMPLE.TEST
Directory Manager password: [password]
Password (confirm): [password]
IPA admin password: [password]
Password (confirm): [password]
NetBIOS domain name: EXAMPLE
Do you want to configure chrony with NTP server or pool address?: no

The IPA Master Server will be configured with:
Hostname:       ipa.example.test
IP address(es): 10.88.0.7
Domain name:    example.test
Realm name:     EXAMPLE.TEST

The CA will be configured with:
Subject DN:   CN=Certificate Authority,O=EXAMPLE.TEST
Subject base: O=EXAMPLE.TEST
Chaining:     self-signed

Continue to configure the system with these values?: yes
```

I am noticing this error instead now after clearing the host directory and retesting the initial configuration:

```
Configuring directory server (dirsrv). Estimated time: 30 seconds
  [1/42]: creating directory server instance
Validate installation settings ...
Create file system structures ...
selinux is disabled, will not relabel ports or files.
[FAILED] Failed to start 389 Directory Server EXAMPLE-TEST..
  [error] CalledProcessError: Command '['systemctl', 'start', 'dirsrv@EXAMPLE-TEST']' returned non-zero exit status 1.
Command '['systemctl', 'start', 'dirsrv@EXAMPLE-TEST']' returned non-zero exit status 1.
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
[FAILED] Failed to start Configure IPA server upon the first start.
[FAILED] Failed deactivating swap /dev/zram0.
[FAILED] Failed unmounting /data.
[FAILED] Failed unmounting /etc/hostname.
[FAILED] Failed unmounting /etc/hosts.
[FAILED] Failed unmounting /etc/resolv.conf.
[FAILED] Failed unmounting /run/lock.
[FAILED] Failed unmounting /run/secrets.
[FAILED] Failed unmounting /tmp/var/tmp.
[FAILED] Failed unmounting /var/log/journal.
[FAILED] Failed unmounting Temporary Directory /tmp.
[FAILED] Failed to start System Power Off.
[DEPEND] Dependency failed for System Power Off.
FreeIPA server configuration failed.
```

`ipserver-install.log` shows:
```
2023-08-11T13:35:54Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 686, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 672, in run_step
    method()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dsinstance.py", line 555, in __create_instance
    sds.create_from_args(general, slapd, backends, None)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 698, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 975, in _install_ds
    ds_instance.start(timeout=60)
  File "/usr/lib/python3.9/site-packages/lib389/__init__.py", line 1071, in start
    subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['systemctl', 'start', 'dirsrv@EXAMPLE-TEST']' returned non-zero exit status 1.

2023-08-11T13:35:54Z DEBUG   [error] CalledProcessError: Command '['systemctl', 'start', 'dirsrv@EXAMPLE-TEST']' returned non-zero exit status 1.
2023-08-11T13:35:54Z DEBUG   File "/usr/lib/python3.9/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/cli.py", line 344, in run
    return cfgr.run()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.9/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.9/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/__init__.py", line 566, in main
    master_install(self)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/install.py", line 278, in decorated
    func(installer)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/server/install.py", line 861, in install
    ds.create_instance(realm_name, host_name, domain_name,
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dsinstance.py", line 324, in create_instance
    self.start_creation(runtime=30)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 686, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 672, in run_step
    method()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dsinstance.py", line 555, in __create_instance
    sds.create_from_args(general, slapd, backends, None)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 698, in create_from_args
    self._install_ds(general, slapd, backends)
  File "/usr/lib/python3.9/site-packages/lib389/instance/setup.py", line 975, in _install_ds
    ds_instance.start(timeout=60)
  File "/usr/lib/python3.9/site-packages/lib389/__init__.py", line 1071, in start
    subprocess.check_output(["systemctl", "start", "dirsrv@%s" % self.serverid], stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
```

From `journalctl -xeu dirsrv@EXAMPLE-TEST.service`:

```
Aug 11 13:39:50 ipa.example.test systemd[1]: Starting 389 Directory Server EXAMPLE-TEST....
░░ Subject: A start job for unit dirsrv@EXAMPLE-TEST.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit dirsrv@EXAMPLE-TEST.service has begun execution.
░░ 
░░ The job identifier is 76.
Aug 11 13:39:50 ipa.example.test systemd[368]: dirsrv@EXAMPLE-TEST.service: ProtectHostname=yes is configured, but UTS namespace setup is prohibited (container manager?), ignoring namespace setup.
Aug 11 13:39:50 ipa.example.test systemd[373]: dirsrv@EXAMPLE-TEST.service: ProtectHostname=yes is configured, but UTS namespace setup is prohibited (container manager?), ignoring namespace setup.
Aug 11 13:39:50 ipa.example.test systemd[378]: dirsrv@EXAMPLE-TEST.service: ProtectHostname=yes is configured, but UTS namespace setup is prohibited (container manager?), ignoring namespace setup.
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.044675562 +0000] - INFO - main - 389-Directory/2.2.4 B2022.347.0000 starting up
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.048335709 +0000] - INFO - main - Setting the maximum file descriptor limit to: 1024
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.620792425 +0000] - INFO - PBKDF2_SHA256 - Based on CPU performance, chose 2048 rounds
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.625766498 +0000] - NOTICE - bdb_start_autotune - found 24272772k physical memory
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.627056486 +0000] - NOTICE - bdb_start_autotune - found 19796832k available
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.628381983 +0000] - NOTICE - bdb_start_autotune - cache autosizing: db cache: 1517048k
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.629833052 +0000] - NOTICE - bdb_start_autotune - total cache size: 1553457408 B;
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.631291289 +0000] - ERR - bdb_no_diskspace - No enough space left on device (/dev/shm/slapd-EXAMPLE-TEST) (65531904 bytes); at least 1708803148 bytes space is needed for db region files
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.632607171 +0000] - ERR - ldbm_back_start - Failed to init database, err=28 Unexpected dbimpl error code
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.633834741 +0000] - ERR - plugin_dependency_startall - Failed to start database plugin ldbm database
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.635706336 +0000] - CRIT - dblayer_setup - dblayer_init failed
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.637019826 +0000] - ERR - ldbm_back_start - Failed to setup dblayer
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.641615001 +0000] - ERR - plugin_dependency_startall - Failed to start database plugin ldbm database
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.643003191 +0000] - ERR - plugin_dependency_startall - Failed to resolve plugin dependencies
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.644290669 +0000] - ERR - plugin_dependency_startall - betxnpreoperation plugin 7-bit check is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.645538886 +0000] - ERR - plugin_dependency_startall - preoperation plugin Account Usability Plugin is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.646876223 +0000] - ERR - plugin_dependency_startall - accesscontrol plugin ACL Plugin is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.648131522 +0000] - ERR - plugin_dependency_startall - preoperation plugin ACL preoperation is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.649501408 +0000] - ERR - plugin_dependency_startall - betxnpreoperation plugin Auto Membership Plugin is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.650829564 +0000] - ERR - plugin_dependency_startall - object plugin Class of Service is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.652074637 +0000] - ERR - plugin_dependency_startall - preoperation plugin deref is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.653417842 +0000] - ERR - plugin_dependency_startall - database plugin ldbm database is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.654713622 +0000] - ERR - plugin_dependency_startall - betxnpreoperation plugin Linked Attributes is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.656072352 +0000] - ERR - plugin_dependency_startall - betxnpreoperation plugin Managed Entries is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.657368140 +0000] - ERR - plugin_dependency_startall - object plugin Multisupplier Replication Plugin is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.658676617 +0000] - ERR - plugin_dependency_startall - object plugin Roles Plugin is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.660040725 +0000] - ERR - plugin_dependency_startall - object plugin Views is not started
Aug 11 13:39:51 ipa.example.test ns-slapd[378]: [11/Aug/2023:13:39:51.661339945 +0000] - ERR - plugin_dependency_startall - extendedop plugin whoami is not started
Aug 11 13:39:51 ipa.example.test systemd[1]: dirsrv@EXAMPLE-TEST.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ An ExecStart= process belonging to unit dirsrv@EXAMPLE-TEST.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 11 13:39:51 ipa.example.test systemd[1]: dirsrv@EXAMPLE-TEST.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit dirsrv@EXAMPLE-TEST.service has entered the 'failed' state with result 'exit-code'.
Aug 11 13:39:51 ipa.example.test systemd[1]: Failed to start 389 Directory Server EXAMPLE-TEST..
░░ Subject: A start job for unit dirsrv@EXAMPLE-TEST.service has failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit dirsrv@EXAMPLE-TEST.service has finished with a failure.
░░ 
░░ The job identifier is 76 and the job result is failed.
```

This is different then what I was receiving before, though had noticed this issue as well when attempting to get this working in the past. At a glance, it seems to be related to the `/dev/shm` size? On the container:

```
[root@ipa data]# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   15G  7.0G  8.1G  47% /
tmpfs                     12G     0   12G   0% /tmp
/dev/mapper/fedora-root   15G  7.0G  8.1G  47% /run
tmpfs                     64M     0   64M   0% /dev
tmpfs                    4.7G  1.8M  4.7G   1% /etc/hosts
tmpfs                     12G     0   12G   0% /tmp/var/tmp
shm                       63M  4.0K   63M   1% /dev/shm
tmpfs                     12G     0   12G   0% /run/lock
devtmpfs                 4.0M     0  4.0M   0% /proc/keys
```

Does the `--shm-size` parameter need to be passed and set to a higher value for the container?

**Comment by adelton** [comment]
@abbra Any idea about the relationship of the `/dev/shm` and read only setup? Do we force the use of `/dev/shm` when some other location that slapd would use is not available (is read only when it shouldn't)?

We saw the shm size issue before but for example in 024676573b6a59b4b361e35808f55739bd793e63 the needed size was three times the current size so I did not worry about it that much. But here we see it to be an order of magnitude higher, so it's weirder.

**Comment by adelton** [comment]
Hmm, is it possible that the amount of memory slapd tries to allocate in `/dev/shm` is somehow based on the free or total space on `/var` or somewhere?

**Comment by adelton** [comment]
I see it had been discussed in https://pagure.io/389-ds-base/issue/49731 as well, in the containers / docker context ...

**Comment by abbra** [comment]
@adelton dirsrv uses `/dev/shm` by default for years now. I feel https://github.com/389ds/389-ds-base/issues/5050 is more relevant here.

**Comment by adelton** [comment]
Comment https://github.com/389ds/389-ds-base/issues/5050#issuecomment-1005603074 points to https://github.com/389ds/389-ds-base/commit/b1efe0d4fff0e209d1f1a2cdeee6c8ef33b7c056 which suggests that in containers, the `/dev/shm` should be avoided for the db_home_dir.

I've tested on Fedora 38 with podman and `quay.io/freeipa/freeipa-server:rocky-9` that the detection logic works there:
```
$ podman exec freeipa-master systemd-detect-virt -c
container-other
$ echo $?
0
```

So why wouldn't it kick in in the Rocky Linux 9 FreeIPA container?

**Comment by adelton** [comment]
@Aetylus Could you please try
```
$ sudo podman run --rm --entrypoint systemd-detect-virt freeipa/freeipa-server:rocky-9 -c
```
to see what it reports for you?

**Comment by Aetylus** [comment]
The output I get is:
```
container-other
```

Not sure if it's helpful or relevant, but this only seems to be an issue for the installation. If I set `--shm-size=2g` for the initial install, then remove the container and start up another without that option, it appears to be working. It picks up the config from the mounted directory and starts FreeIPA:

```
Mount failed for selinuxfs on /sys/fs/selinux:  No such file or directory
Wed Aug 16 01:02:26 UTC 2023 /usr/sbin/ipa-server-configure-first upgrade
FreeIPA server is already configured, starting the services.
Wed Aug 16 01:02:38 UTC 2023 /usr/sbin/ipa-server-configure-first update-self-ip-address
FreeIPA server does not run DNS server, skipping update-self-ip-address.
FreeIPA server started.
```

**Comment by adelton** [comment]
That
```
Mount failed for selinuxfs on /sys/fs/selinux:  No such file or directory
```
caught my eye -- that indicates something is wrong on that machine, or at least different from my Fedora 38.

What do
```
$ ls -la /sys/fs/cgroup/cgroup.controllers
```
```
$ mount | grep cgroup
```
return on your system?

Also, can you retry with podman upgraded to 4.6.1-1.fc38?

**Comment by Aetylus** [comment]
For those commands:
```sh
$ ls -la /sys/fs/cgroup/cgroup.controllers
-r--r--r--. 1 root root 0 Aug 14 17:22 /sys/fs/cgroup/cgroup.controllers
```
```
$ mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate,memory_recursiveprot)
```

As for updating to podman 4.6.1-1.fc38 and starting another container to test the installation, that does appear to work without `--shm-size=2g` added. Additionally, after upgrading and restarting the existing container, I'm seeing the following in the logs instead:

```
Failed to set RLIMIT_CORE: Operation not permitted
Mon Aug 21 17:31:13 UTC 2023 /usr/sbin/ipa-server-configure-first upgrade
FreeIPA server is already configured, starting the services.
Mon Aug 21 17:31:24 UTC 2023 /usr/sbin/ipa-server-configure-first update-self-ip-address
FreeIPA server does not run DNS server, skipping update-self-ip-address.
FreeIPA server started.
```

**Comment by adelton** [comment]
Yep, that matches what I see.

So can we conclude that something in podman 4.5.1 confused the FreeIPA installer that it tried to put the directory server data to `/dev/shm`, rather than where there is enough space, and the latest podman version has that problem resolved?

**Comment by Aetylus** [comment]
I've done several other tests and that seems to have been the case! Since updating Podman, haven't run into the issue with `--read-only`.
