### ISSUE TITLE
Two crashes: pki and httpd

### ISSUE THREAD

**Issue by systemcrash** [freeipa/freeipa-container#565]
Not strictly a container issue, but due to the yuge amount of on-boarding friction just to report these bugs properly... no thanks. 

Two python trace-backs result when using `freeipa/freeipa-server:rocky-9-4.10.1`, and running `/usr/sbin/ipa-server-configure-first`

# Traceback 1

The first one is mysterious AF. The last thing logged was:
```
2023-10-26T00:00:13Z DEBUG stderr=Failed to get unit file state for ntpd.service: No such file or directory

2023-10-26T00:00:13Z DEBUG Starting external process
...skipping...
    'sensitive_parameters': '\n'
                            'pki_admin_password\n'
                            'pki_backup_password\n'
                            'pki_client_database_password\n'
                            'pki_client_pin\n'
    'pki_tomcat_work_catalina_path': '/var/lib/pki/pki-tomcat/work/Catalina',
    'pki_tomcat_work_path': '/var/lib/pki/pki-tomcat/work',
    'pki_transport_tag': 'transport',
    'pki_transport_token': 'internal',
    'pki_use_oaep_rsa_keywrap': 'False',
    'pki_use_pss_rsa_signing_algorithm': 'False',
    'pki_user': 'pkiuser',
    'pki_user_deployment_cfg': '/tmp/tmp4mg9qx_w',
    'pki_user_deployment_cfg_replica': '/etc/sysconfig/pki/tomcat/pki-tomcat/ca/deployment.cfg',
    'pki_user_deployment_cfg_spawn_archive': '/var/log/pki/pki-tomcat/ca/archive/spawn_deployment.cfg.20231026000110',
    'sensitive_parameters': '\n'
                            'pki_admin_password\n'
                            'pki_backup_password\n'
                            'pki_client_database_password\n'
                            'pki_client_pin\n'
                            'pki_client_pkcs12_password\n'
                            'pki_clone_pkcs12_password\n'
                            'pki_ds_password\n'
                            'pki_external_pkcs12_password\n'
                            'pki_pkcs12_password\n'
                            'pki_one_time_pin\n'
                            'pki_pin\n'
                            'pki_replication_password\n'
                            'pki_security_domain_password\n'
                            'pki_server_database_password\n'
                            'pki_server_pkcs12_password\n'
                            'pki_token_password',
    'spawn_scriplets': '\n'
                       'initialization\n'
                       'infrastructure_layout\n'
                       'instance_layout\n'
                       'subsystem_layout\n'
                       'webapp_deployment\n'
                       'security_databases\n'
                       'selinux_setup\n'
                       'keygen\n'
                       'fapolicy_setup\n'
                       'configuration\n'
                       'finalization'}
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/pki/server/pkispawn.py", line 1030, in <module>
    main(sys.argv)
  File "/usr/lib/python3.9/site-packages/pki/server/pkispawn.py", line 559, in main
    pkilogging.enable_pki_logger(args.log_file)
  File "/usr/lib/python3.9/site-packages/pki/server/deployment/pkilogging.py", line 56, in enable_pki_logger
    pathlib.Path(filename).touch()
  File "/usr/lib64/python3.9/pathlib.py", line 1315, in touch
    fd = self._raw_open(flags, mode)
  File "/usr/lib64/python3.9/pathlib.py", line 1127, in _raw_open
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/pki/pki-ca-spawn.20231026000110.log'

2023-10-26T00:01:10Z CRITICAL Failed to configure CA instance
2023-10-26T00:01:10Z CRITICAL See the installation logs and the following files/directories for more information:
2023-10-26T00:01:10Z CRITICAL   /var/log/pki/pki-tomcat
2023-10-26T00:01:10Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 686, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/service.py", line 672, in run_step
    method()
  File "/usr/lib/python3.9/site-packages/ipaserver/install/cainstance.py", line 651, in __spawn_instance
    DogtagInstance.spawn_instance(
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dogtaginstance.py", line 227, in spawn_instance
    self.handle_setup_error(e)
  File "/usr/lib/python3.9/site-packages/ipaserver/install/dogtaginstance.py", line 604, in handle_setup_error
    raise RuntimeError(
         Stopping IPA Custodia Service...
         Stopping Kerberos 5 Password-changing and Administration...
         Stopping Kerberos 5 KDC...
```

Ya can't `touch` a file until the path to it exists. Checking the logs folder, one finds that no `pki/` folder exists(!). 

# Solution 1
`mkdir -p /var/logs/pki` and first problem was fixed. 

# Traceback 2

The second problem was even more mysterious and time-consuming AF. 

It looked like:
```
  [14/22]: publish CA cert
  [15/22]: clean up any existing httpd ccaches
  [16/22]: enable ccache sweep
  [17/22]: configuring SELinux for httpd
  [18/22]: create KDC proxy config
  [19/22]: enable KDC proxy
         Starting One-time temporary TLS key generation for httpd.service...
[  OK  ] Finished One-time temporary TLS key generation for httpd.service.
         Starting The Apache HTTP Server...
[FAILED] Failed to start The Apache HTTP Server.
See 'systemctl status httpd.service' for details.
  [error] CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'start', 'httpd.service'] returned non-zero exit status 1: 'Job for httpd.service failed because the control process exited with error code.\nSee "systemctl status httpd.service" and "journalctl -xeu httpd.service" for details.\n')
CalledProcessError(Command ['/bin/systemctl', 'start', 'httpd.service'] returned non-zero exit status 1: 'Job for httpd.service failed because the control process exited with error code.\nSee "systemctl status httpd.service" and "journalctl -xeu httpd.service" for details.\n')
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
FreeIPA server configuration failed.
[FAILED] Failed to start Configure IPA server upon the first start.
See 'systemctl status ipa-server-configure-first.service' for details.
[  OK  ] Stopped target Minimal target for containerized FreeIPA server.
...
```

After eventually getting into the container via bash, and running `journalctl -xeu httpd.service`, it talks about:

```
Oct 26 00:25:12 ipa.hq.example.com systemd[1]: Starting The Apache HTTP Server...
░░ Subject: A start job for unit httpd.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░
░░ A start job for unit httpd.service has begun execution.
░░
░░ The job identifier is 176.
Oct 26 00:25:14 ipa.hq.example.com ipa-httpd-kdcproxy[3959]: ipa: INFO: KDC proxy enabled
Oct 26 00:25:14 ipa.hq.example.com ipa-httpd-kdcproxy[3959]: ipa-httpd-kdcproxy: INFO     KDC proxy enabled
Oct 26 00:25:14 ipa.hq.example.com httpd[3964]: (2)No such file or directory: AH02291: Cannot access directory '/etc/httpd/logs/' for main error log
Oct 26 00:25:14 ipa.hq.example.com httpd[3964]: (2)No such file or directory: AH02291: Cannot access directory '/etc/httpd/logs/' for error log of vhost defined at /etc/httpd/conf.d/ss>
Oct 26 00:25:14 ipa.hq.example.com httpd[3964]: AH00014: Configuration check failed
Oct 26 00:25:14 ipa.hq.example.com systemd[1]: httpd.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░
░░ An ExecStart= process belonging to unit httpd.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Oct 26 00:25:14 ipa.hq.example.com systemd[1]: httpd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░
░░ The unit httpd.service has entered the 'failed' state with result 'exit-code'.
Oct 26 00:25:14 ipa.hq.example.com systemd[1]: Failed to start The Apache HTTP Server.
░░ Subject: A start job for unit httpd.service has failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░
░░ A start job for unit httpd.service has finished with a failure.
░░
░░ The job identifier is 176 and the job result is failed.
```

Poking around in the problem folder:
```
[root@ipa /]# ls -l /etc/httpd/logs/
ls: cannot access '/etc/httpd/logs/': No such file or directory
[root@ipa /]# ls -l /etc/httpd/
total 4
lrwxrwxrwx. 1 root root   21 Oct 25 04:29 alias -> /data/etc/httpd/alias
lrwxrwxrwx. 1 root root   20 Oct 25 04:29 conf -> /data/etc/httpd/conf
lrwxrwxrwx. 1 root root   22 Oct 25 04:29 conf.d -> /data/etc/httpd/conf.d
drwxr-xr-x. 2 root root 4096 Oct 25 04:29 conf.modules.d
lrwxrwxrwx. 1 root root   19 May 16 20:21 logs -> ../../var/log/httpd
lrwxrwxrwx. 1 root root   29 May 16 20:21 modules -> ../../usr/lib64/httpd/modules
lrwxrwxrwx. 1 root root   10 May 16 20:21 run -> /run/httpd
lrwxrwxrwx. 1 root root   19 May 16 20:21 state -> ../../var/lib/httpd
```

# Solution 2
So again, `/var/logs/httpd/` folder didn't exist either. `mkdir -p /var/logs/httpd` and restart the installer...

**Comment by adelton** [comment]
Is this some ChatGPT-generated issue?

If this is not a container issue, why is this reported here?

The first description first talks about `/logs/pki/blah-98273459872345.log` but then the traceback is about `/var/log/pki/pki-ca-spawn.20231026000110.log`.

The second solution first talks about `/logs/httpd` but the systemd unit error is about `/etc/httpd/logs/`.

How was the container created and started, exactly?

**Comment by systemcrash** [comment]
> 
> The second solution first talks about `/logs/httpd` but the systemd unit error is about `/etc/httpd/logs/`.

Yeah, it did. `/var/...`

> 
> How was the container created and started, exactly?

Absolutely very real issues. Folders that don't exist. 

Container was (attempted to) started exactly as detailed here `https://hub.docker.com/r/freeipa/freeipa-server`

**Comment by adelton** [comment]
There are multiple commands there and I asked for the exact command. So far we don't even know if you used `docker` or `podman`. While at it, please provide information about the host operating system.

**Comment by systemcrash** [comment]
```
docker -v
Docker version 24.0.6, build ed223bc
```

```
uname -a
Linux freeipa.example.com 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 16 09:55:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Before we go down rabbit holes, shouldn't we ask why every other step of the process succeeds, except for those that require the presence of `pki` and `httpd` folders in the `/var/log` folder? There are a bunch of other processes that succeed in creating subfolders in `/var/log`.

7th attempt:
```
docker run --name ipa -ti  --sysctl net.ipv6.conf.all.disable_ipv6=0   -h ipa.example.test --read-only     -v ./ipa-data:/data:Z  freeipa/freeipa-server:rocky-9-4.10.1
```

17th (ish) attempt:
```sh
docker run --name freeipa-freeipa-1 -ti  --sysctl net.ipv6.conf.all.disable_ipv6=0 -h ipa.example.test  -v ./ipa-data:/data:Z freeipa/freeipa-server:rocky-9-4.10.1
```

When it became evident that the /var/log folder was problematic, I started to do:
```
docker run --name freeipa-freeipa-1 -ti  --sysctl net.ipv6.conf.all.disable_ipv6=0  -h ipa.example.test  -v ./ipa-data:/data:Z -v ./logs/:/var/log freeipa/freeipa-server:rocky-9-4.10.1
```

Same result, but I could now more easily create the missing folders when it becacme evident that they were the problem.

**Comment by adelton** [comment]
So in the absence of clear answer, we shall assume that the OS on the host is Rocky Linux 9 with SELinux enforcing enabled, the docker is a `docker-ce` installed from https://download.docker.com/linux/centos/docker-ce.repo, that the docker daemon is configured with user namespace remapping, and you are running this as a non-root user which also means that the `ipa-data` directory is owned by the uid listed in /etc/subuid for user `dockremap`, let's assume 165536.

We will go down the rabbit hole if necessary but we will start the debugging at the beginning, in a systematic fashion. We won't kick off with any generic questions like "why every other step of the process succeeds?". Well, I could tell you right away that the problem is caused by that `-v ./logs/:/var/log` which was supposed to fix whatever was failing before that in those previous 17+ attempts, but I won't do that because you wouldn't believe me.

We will also try to be very precise with any data we show.

So please kill any of the previous containers you might have around, remove any content from that `ipa-data` from any of the 20 attempts you made, remove that `logs` directory so it does not tempt you, and start with an empty `ipa-data` directory, with proper ownership:

```
$ ls -la ipa-data/
total 0
drwxr-xr-x. 2 165536 165536   6 Oct 26 17:11 .
drwx--x--x. 5 test   test   125 Oct 26 17:06 ..
```

Have a second terminal ready.

In the first one, run the
```
$ docker run --name ipa -ti  --sysctl net.ipv6.conf.all.disable_ipv6=0   -h ipa.example.test --read-only     -v ./ipa-data:/data:Z  freeipa/freeipa-server:rocky-9-4.10.1
```
command and see it reach
```
systemd 252-14.el9_2.3.0.1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
```
and later
```
Do you want to configure integrated DNS (BIND)? [no]:
```

Before proceeding any further, in the second terminal check the content of that `ipa-data` directory:
```
$ ls -la ipa-data
total 12
drwxr-xr-x.  8 165536 165536  133 Oct 26 17:12 .
drwx--x--x.  5 test   test    125 Oct 26 17:06 ..
-rw-r--r--.  1 165536 165536   37 Oct 25 06:29 build-id
drwxr-xr-x.  4 165536 165536   28 Oct 25 06:29 .configfiles
drwxr-xr-x.  4 165536 165536   28 Oct 25 06:29 .configfiles-noreplace
drwxr-xr-x. 19 165536 165536 4096 Oct 25 06:29 etc
-rw-r--r--.  1 165536 165536   17 Oct 26 17:12 hostname
drwxr-xr-x.  3 165536 165536   21 Oct 25 06:29 root
drwxr-xr-x.  3 165536 165536   19 Oct 25 06:29 usr
drwxr-xr-x.  6 165536 165536   57 Oct 26 17:12 var
$ ls -la ipa-data/var/log
total 100
drwxr-xr-x. 9 165536 165536  4096 Oct 26 17:12 .
drwxr-xr-x. 6 165536 165536    57 Oct 26 17:12 ..
-rw-rw----. 1 165536 165558     0 Oct 25 06:29 btmp
drwxr-xr-x. 2 165536 165536     6 Sep 27 01:32 dirsrv
drwx------. 2 165536 165536     6 May 16 22:21 httpd
drwxr-xr-x. 3 165536 165536    25 Oct 25 06:29 ipa
-rw-r--r--. 1 165536 165536   118 Oct 26 17:12 ipa-server-configure-first.log
-rw-------. 1 165536 165536  4984 Oct 26 17:12 ipaserver-install.log
-rw-r--r--. 1 165536 165536     0 Oct 26 17:12 ipa-server-run.log
drwxr-xr-x. 3 165536 165536    46 Oct 26 17:12 journal
-rw-rw-r--. 1 165536 165558 83512 Oct 25 06:29 lastlog
drwxr-xr-x. 2 165536 165536     6 Apr 25  2023 pki
drwx------. 3 165536 165536    17 Oct 25 06:29 samba
drwxr-x---. 2 165820 165816     6 Aug  2 08:31 sssd
-rw-rw-r--. 1 165536 165558     0 Oct 25 06:29 wtmp
```

Please show the output of the above commands in the above situations if they differ in a significant way from the one I got.

**Comment by systemcrash** [comment]
```
[root@freeipa freeipa]# ls -la ipa-data
total 16
drwxr-xr-x.  8 100000 100000  133 Oct 27 01:09 .
drwxr-xr-x.  6 root   root   4096 Oct 27 01:09 ..
-rw-r--r--.  1 100000 100000   37 Oct 25 06:29 build-id
drwxr-xr-x.  4 100000 100000   28 Oct 25 06:29 .configfiles
drwxr-xr-x.  4 100000 100000   28 Oct 25 06:29 .configfiles-noreplace
drwxr-xr-x. 19 100000 100000 4096 Oct 25 06:29 etc
-rw-r--r--.  1 100000 100000   17 Oct 27 01:09 hostname
drwxr-xr-x.  3 100000 100000   21 Oct 25 06:29 root
drwxr-xr-x.  3 100000 100000   19 Oct 25 06:29 usr
drwxr-xr-x.  6 100000 100000   57 Oct 27 01:09 var
```

```
[root@freeipa freeipa]# ls -la ipa-data/var/log/
total 100
drwxr-xr-x. 9 100000 100000  4096 Oct 27 01:09 .
drwxr-xr-x. 6 100000 100000    57 Oct 27 01:09 ..
-rw-rw----. 1 100000 100022     0 Oct 25 06:29 btmp
drwxr-xr-x. 2 100000 100000     6 Sep 27 01:32 dirsrv
drwx------. 2 100000 100000     6 May 16 22:21 httpd
drwxr-xr-x. 3 100000 100000    25 Oct 25 06:29 ipa
-rw-r--r--. 1 100000 100000   118 Oct 27 01:09 ipa-server-configure-first.log
-rw-------. 1 100000 100000  4981 Oct 27 01:09 ipaserver-install.log
-rw-r--r--. 1 100000 100000     0 Oct 27 01:09 ipa-server-run.log
drwxr-xr-x. 3 100000 100000    46 Oct 27 01:09 journal
-rw-rw-r--. 1 100000 100022 83512 Oct 25 06:29 lastlog
drwxr-xr-x. 2 100000 100000     6 Apr 25  2023 pki
drwx------. 3 100000 100000    17 Oct 25 06:29 samba
drwxr-x---. 2 100284 100280     6 Aug  2 08:31 sssd
-rw-rw-r--. 1 100000 100022     0 Oct 25 06:29 wtmp
```

Incredible. The problem never manifests when the designer is around. So we care not to spend another minute on this problem which is evidently mine. Thanks for your time.
