### ISSUE TITLE
Ipa-install fail: Certificate not found: caSigningCert cert-pki-ca

### ISSUE THREAD

**Issue by antnjakushin** [freeipa/freeipa-container#570]
Host OS: AlmaLinux 8 (with podman version 4.4.1)
Image: freeipa/freeipa-server:fedora-37
We are trying to launch a container using podman. I use this compose file:

```
version: '3'
services:
  freeipa:
    image: freeipa/freeipa-server:fedora-37
    container_name: freeipa
    hostname: dc01.example.com
    restart: always
    volumes:
      - freeipa-data:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command:
      - ipa-server-install
    environment:
      - IPA_SERVER_INSTALL_OPTS=-U --domain=example.com --realm=EXAMPLE.COM --admin-password=test1234 --ds-password=test1234 --setup-dns --no-host-dns --forwarder=8.8.8.8 --allow-zone-overlap --no-ntp
      - DEBUG_TRACE=1
      - DEBUG_NO_EXIT=1
    networks:
      macvlan_dmz:
        ipv4_address: 10.1.1.1
    cap_add:
      - CAP_AUDIT_WRITE
      - NET_ADMIN
volumes:
  freeipa-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.1.1.2,rw,nfsvers=4"
      device: "10.1.1.2:/var/podman/freeipa"

networks:
  macvlan_dmz:
    external: true

```

And I get this error:

```
[freeipa] | Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
[freeipa] |   [1/30]: configuring certificate server instance
[freeipa] |   [error] RuntimeError: CA configuration failed.
[freeipa] | + ret=123
[freeipa] | + echo 'FreeIPA server configuration failed.'
[freeipa] | FreeIPA server configuration failed.
[freeipa] | + exit 123
[freeipa] | + mark_exit_code
[freeipa] | + exit_code=123
[freeipa] | + echo 123
[freeipa] | + exit 123
```

ipaserver-install.log

```
INFO: Storing cert and request for signing
INFO: Importing signing cert into NSS database
DEBUG: NSSDatabase.add_cert(caSigningCert cert-pki-ca)
DEBUG: Command: pki -d /etc/pki/pki-tomcat/alias -C /tmp/tmpyvgmqlz4/password.txt nss-cert-import --format PEM --debug caSigningCert cert-pki-ca
INFO: Initializing NSS
INFO: Logging into internal token
INFO: Using internal token
FINE: NSSDatabase: Storing password into /tmp/nss-password-14450567972036567035.txt
FINE: NSSDatabase: Command: certutil -A -d /etc/pki/pki-tomcat/alias -f /tmp/nss-password-14450567972036567035.txt -a -n "caSigningCert cert-pki-ca" -t ,, -i /tmp/nss-cert-7075474161335672400.crt
INFO: Initializing CA

2023-11-23T15:05:47Z CRITICAL Failed to configure CA instance
2023-11-23T15:05:47Z CRITICAL See the installation logs and the following files/directories for more information:
2023-11-23T15:05:47Z CRITICAL   /var/log/pki/pki-tomcat
2023-11-23T15:05:47Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ipaserver/install/service.py", line 686, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.11/site-packages/ipaserver/install/service.py", line 672, in run_step
    method()
  File "/usr/lib/python3.11/site-packages/ipaserver/install/cainstance.py", line 650, in __spawn_instance
    DogtagInstance.spawn_instance(
  File "/usr/lib/python3.11/site-packages/ipaserver/install/dogtaginstance.py", line 227, in spawn_instance
    self.handle_setup_error(e)
  File "/usr/lib/python3.11/site-packages/ipaserver/install/dogtaginstance.py", line 604, in handle_setup_error
    raise RuntimeError(
RuntimeError: CA configuration failed.

2023-11-23T15:05:47Z DEBUG   [error] RuntimeError: CA configuration failed.
2023-11-23T15:05:47Z DEBUG Removing /root/.dogtag/pki-tomcat/ca

```
/var/log/pki/pki-tomcat/ca/debug.2023-11-23.log
```
2023-11-23 15:05:45 [https-jsse-nio-8443-exec-7] INFO: LDAPSession: Retrieving cn=1,ou=ca, ou=requests,o=ipaca
2023-11-23 15:05:45 [https-jsse-nio-8443-exec-7] INFO: LDAPSession: Modifying cn=1,ou=ca, ou=requests,o=ipaca
2023-11-23 15:05:47 [https-jsse-nio-8443-exec-8] INFO: CAInstallerService: Initializing subsystem
2023-11-23 15:05:47 [https-jsse-nio-8443-exec-8] INFO: CertificateAuthority: Initializing cert signing unit
2023-11-23 15:05:47 [https-jsse-nio-8443-exec-8] SEVERE: Object certificate not found. Error Certificate not found: caSigningCert cert-pki-ca: Certificate not found: caSigningCert cert-pki-ca
Certificate not found: caSigningCert cert-pki-ca: Certificate not found: caSigningCert cert-pki-ca
```

I can only get around this error if I choose not to use a persistent volume on the NFS.
Export options on the NFS server:
`/var/podman     <world>(sync,wdelay,hide,no_subtree_check,sec=sys,rw,insecure,no_root_squash,no_all_squash)`

**Comment by adelton** [comment]
General comments:

Fedora 37 will reach end of life in less than two weeks, you might reconsider the use of such old version.

Why are the capabilities
```
      - CAP_AUDIT_WRITE
      - NET_ADMIN
```
needed in your setup? For years we've been testing and running the FreeIPA containers without any extra capabilities needed.

Since the factor that makes the setup pass / fail is having the volume on the NFS, that's probably the next thing to focus your investigation. I don't think there are many (any?) FreeIPA installations where `/var/lib/ipa` would be on a NFS, so maybe you want to remove the containerization from the mix, install IPA on that AlmaLinux 8 host, mount `/var/lib/ipa` from that NFS server, and see if you are able to finish the `ipa-server-install` and CA configuration that way.

**Comment by antnjakushin** [comment]
Switching to another Fedora version (fc39&fc38) helped, thanks.
